### ISSUE TITLE
UI updation

### ISSUE THREAD

**Issue by StephenStolk** [VanshKing30/FoodiesWeb#10]
Making the navbar responsive.
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/d9b78de2-6c2c-4f37-bfaa-d7f8912f24e0)

Small screens:
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/80755aa2-5034-4c87-9666-0f8ab2b60191)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/76433d0f-76b9-43f2-ad4e-3c5b583ad753)

**Comment by StephenStolk** [comment]
I want to work on this. Please assign this to me is issue gets accepted.

**Comment by VanshKing30** [comment]
@StephenStolk Cool !! Make it Responsive , I am assigning this issue to you !!
