### ISSUE TITLE
Responsive Navbar

### ISSUE THREAD

**Issue by The-Phoenics** [VanshKing30/FoodiesWeb#100]
Hi @VanshKing30, I've noticed following problems with navbar:

1. Currently there is no navbar styling to indicate the current page user is navigating.
2. Navbar is not responsive on smaller screen sizes.
3. Nav elements text(not centered) styling is quite not desirable:
![Screenshot_2024_0512_230852.jpg](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/b19302a9-d57d-4ea2-a592-e464a23c141e)

I would like to work on this for GSSoC'23. Can you please assign this to me?

**Comment by VanshKing30** [comment]
What changes can you make , please share some screenshots

**Comment by The-Phoenics** [comment]
Hey @VanshKing30 , these are some issues which I can work on a fix:

Hover color on login button doesn't look as good in my opinion: 
![3](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/e2c35bfc-184c-4971-a903-fe02b51b6bbe)
![1](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/37cfb3bb-7a50-475b-bb39-a366040af239)

Text in nav elements is not center aligned:
![2](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/0fcb80b3-838d-426a-9a90-01688762efb7)

Extra padding or left of navbar on small size screen
![4](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/0c3b3542-3835-430b-a2cb-46c05377c6b5)

And also a small pop-like framer motion animation would look good on nav elements, and some highlight inidicating which page is active.

**Comment by VanshKing30** [comment]
@The-Phoenics How long will it take you to solve this issue ?

**Comment by The-Phoenics** [comment]
> @The-Phoenics How long will it take you to solve this issue ?

I can do these fixes by tomorrow.
