### ISSUE TITLE
UI BUG: Visibility of Scroll bar

### ISSUE THREAD

**Issue by StephenStolk** [VanshKing30/FoodiesWeb#101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The scrollbar is visible. It would be a professional appeal to remove the scrollbar from application.

Current: (scrollbar is visible)

![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/8c092bcf-c370-4da4-a03f-6bdb7b20275f)

After changes: (Scrollbar is removed, scrolling is preserved)

![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/7aeaf9ba-20a9-478f-9d0b-ec43b99c7461)

- Preserving scrolling
- Removing scrollbar visibility.

I want to take up this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by StephenStolk** [comment]
@VanshKing30 
Please assign this one issue to me.

**Comment by VanshKing30** [comment]
Assigner you the issue

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.

**Comment by VanshKing30** [comment]
@StephenStolk Have you solved the issue ?

**Comment by StephenStolk** [comment]
@VanshKing30 
Yes. I have already made the PR
