### ISSUE TITLE
BUG: user is not logged in then access the Home,About ...route

### ISSUE THREAD

**Issue by Varsani2520** [VanshKing30/FoodiesWeb#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the issue is when user is not logged in then redirect the login page 
user have no access the other route for security 
it's a very Important for e-commerce website.
image 1: default route: where display login page for user authentication
![image](https://github.com/VanshKing30/FoodiesWeb/assets/137641079/c549453f-4281-424d-a3b0-8440c4943426)
image 2: issue is when user is not logged in then not go to main Routes like Home,About ,News ..:
![image](https://github.com/VanshKing30/FoodiesWeb/assets/137641079/2107f634-d783-4a78-92dc-bed73a1ee25e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
This iusse has alredy been taken !
