### ISSUE TITLE
Storing Canteen/Dish/Food Images For Showcasing In Home Page

### ISSUE THREAD

**Issue by TejasNasre** [VanshKing30/FoodiesWeb#11]
<h1>Currently The Images In Home Pages Of Canteen Are Static</h1>
<p>Adding Multer And Cloudinary Integration In Backend For Storing Images In Database.Also Wants To Update The Schema And Handling Response.</p>
<p>Updation In Frontend For Handling Files And Showcasing In Frontend</p>
<p>By This We Can Generate Dynamic Images From Backend And The Canteen Owner Get More Attraction Towards His Canteen.</p>
Current HomePage : 
![home](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/efee0757-0cab-41b5-86c1-dd9e7bd1de09)

**Comment by TejasNasre** [comment]
I Am Contributor In GSSoC'24 Please Assign This Issue To Me.

**Comment by VanshKing30** [comment]
Thats seems like a good enhancement in the website , I am assigning this issue to you !! Create a Pull request after solving the issue and do send the later screenshot after completing the task!!

**Comment by TejasNasre** [comment]
Thanks To Assign Me Issue @VanshKing30

**Comment by TejasNasre** [comment]
Successfully Implement the feature  : file upload to cloudinary and store the food/canteen/etc images.
![output](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/8a2d62c2-3cbf-497f-a342-5dfda52054e1)

App is Also Running without error
![run successfully](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/2987dbf1-fbb2-4d2f-b116-1dcc07f52d1a)

Raising PR Tomorrow Because Of Some Unwanted Changes And Requesting @VanshKing30 To Make Issue Level 3

**Comment by VanshKing30** [comment]
Cool Buddy !! Nice Work Done

**Comment by TejasNasre** [comment]
@VanshKing30  PR Raised #61 This Feature is added to store images in cloudinary instead of database we get the signal image url.
we want to integrate it with when canteen owner adds his canteen info and with info we want to get canteen image so its another issue to integrate and also we need to change the frontend. we need to work more on this so i am requesting to raise issue and assign it to me or i will raise issue.i have my sem exams that's why i am not raising issues more 😁Thank you

**Comment by VanshKing30** [comment]
You only have worked on the backend part right ?

**Comment by TejasNasre** [comment]
yes i have exam so i don't get time but i want to get update full feature in backend and frontend also in upcoming days i will create issue so please assign me
