### ISSUE TITLE
BUG: Showing Rules on Register page is not Good according to Industry level

### ISSUE THREAD

**Issue by HardCoder404** [VanshKing30/FoodiesWeb#110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In Register page, at the bottom there is rules are mentioned for entering valid data., but according to industry the validation form are more prefered. In place of showing all the rules we just add a form validation. It will enhance the quality of the web. 

Assign me this issue, I'll be glad to work on that, as i 've already submitted many of the issues and bugs on other projects as a contributor.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
What changes will you make ?
