### ISSUE TITLE
@VanshKing30 yup I will be able to solve

### ISSUE THREAD

**Issue by Niharika0104** [VanshKing30/FoodiesWeb#119]
@VanshKing30 yup I will be able to solve 
I worked on this kind of issues before

_Originally posted by @Niharika0104 in https://github.com/VanshKing30/FoodiesWeb/issues/94#issuecomment-2106248802_

**Comment by VanshKing30** [comment]
Assigned you the issue !!

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.
