### ISSUE TITLE
Assigning Middleware Part for Canteen Backend part

### ISSUE THREAD

**Issue by rajankumar77915** [VanshKing30/FoodiesWeb#12]
In  canteen food management system, I have identified a critical security concern where anyone, including students, can delete or add food items. To address this, we need to implement middleware that ensures only authorized personnel can make changes to the food inventory.
Kindly assign it to me under GSSOC'24.

**Comment by VanshKing30** [comment]
Could you please clarify the issue you added to my repository? I want to ensure I understand it fully. Thanks!

**Comment by rajankumar77915** [comment]
Only Canteen(admin) can perform actions such as addLunchDish, removeLunchDish, addDinnerDish, getCanteenDashboard, addBreakfastDish, and removeBreakfastDish
Currently, users(normal) can access Canteen(admin) API, which is not secure. Hence, security needs to be added.

i can add security so **only** Canteen(admin) can access canteen routes like,
router.post('/:id/breakfast/add', canteenController.addBreakfastDish);
router.delete('/:id/breakfast/remove', canteenController.removeBreakfastDish);       ...

**Comment by Tarun2605** [comment]
I am interested in resolving this issue. Please assign it to me.

**Comment by VanshKing30** [comment]
Hey @rajankumar77915 

I've assigned you the task of adding security measures to restrict access to canteen routes for only Canteen (admin) roles. Looking forward to seeing your solution!

Best regards,
Vansh

**Comment by ayann07** [comment]
I would like to do this task under GSSOC'24.

**Comment by mutcherlarahulkumar** [comment]
Subject: Request to Contribute and Task Assignment

Dear @VanshKing30 ,

I hope this message finds you well. My name is Rahul Kumar and I'm writing to express my interest in contributing to Foodies. I've been following the project for some time and I'm impressed by the work being done.

I would greatly appreciate it if you could consider assigning me this task. I'm eager to collaborate with the team and contribute to the project's success.

Thank you for your time and consideration. I look forward to hearing from you soon.

Best regards,
Rahul Kumar
