### ISSUE TITLE
Feat: API and frontend for Profile page with editing user details

### ISSUE THREAD

**Issue by exploring-solver** [VanshKing30/FoodiesWeb#120]
# User Profile Feature

## Objective
The goal is to enhance the user experience by allowing users to easily edit their profile details and view their profile information in a user-friendly manner.

## Features
1. API endpoints supporting CRUD operations for user details editing.
2. Frontend with form elements for editing user details and displaying profile information.
3. Responsiveness and accessibility standards in design and development.

## Timeline
The feature will be completed within 2 days.

## Screenshots
![Demo UI](https://github.com/VanshKing30/FoodiesWeb/assets/123443485/4650a29a-71b2-4caf-ad49-1a5b98d12df8)

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/123443485/e66bf7ad-872c-47e2-9076-3a81ed5ccc09)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Will you be able to do both the frontend and the backend part ?

**Comment by Anand-shreya** [comment]
i want to work on it

**Comment by VanshKing30** [comment]
@Anand-shreya Explain me the approach to do , take the task ;)

**Comment by exploring-solver** [comment]
> Will you be able to do both the frontend and the backend part ?

Yes surely I will be able to do both tasks with a controller for profile details and a route to GET the details and once the user is logged in I will show the Profile icon at top of Navbar with a profile page that sends a GET request to get User's profile Details.
I have worked with MERN projects multiple times.
Please assign this issue to me.

If you want I can do the project in 2 PR's if the task is too big for level 3.

**Comment by princyym** [comment]
Can I try on this, will you assign this to me @VanshKing30 ?

**Comment by kashish-51** [comment]
@VanshKing30 ,can you please assign this project to me?

**Comment by exploring-solver** [comment]
> Done !! Assigned you the task !! Raise the PR when done 
> In case any issue message me on discord : Vansh5238

Thank you so much for the opportunity. Will raise a PR by the end of this week.

**Comment by VanshKing30** [comment]
@exploring-solver Have you completed the task ??

**Comment by exploring-solver** [comment]
@VanshKing30 Yes I will create a PR today.
