### ISSUE TITLE
Feat: Adding Loader to Signup and Login page

### ISSUE THREAD

**Issue by Saksham1411** [VanshKing30/FoodiesWeb#121]
### **Problem**
When I am creating a new user it takes some time to complete the request but it looks like the website gets hung which gives a poor User experience 

### **Solution**
I Can add a spinner loader to the signup/login button which will enhance the user experience and It doesn't fells website is not working 

### Add ScreenShots

https://github.com/VanshKing30/FoodiesWeb/assets/101385720/e00e63dc-75a4-49f1-9c2d-b23500f5f576

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham1411** [comment]
As a GSsoc'24 contributor. I want to address this issue. I request you to assign this to me @VanshKing30

**Comment by VanshKing30** [comment]
This issue has alredy been solved by someone !!
