### ISSUE TITLE
Feat: sign up button should be more visible 

### ISSUE THREAD

**Issue by kapilG0** [VanshKing30/FoodiesWeb#122]
### Describe the feature

On login page there is sign up button option as well which need to be more visible 

### Add ScreenShots

![Screenshot_20240514_120730](https://github.com/VanshKing30/FoodiesWeb/assets/59639410/7adc41ca-6a97-4110-ae9c-9dc898b84ff2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @VanshKing30 can you please assign this issue to me under gssoc

**Comment by VanshKing30** [comment]
No need !!
