### ISSUE TITLE
Feat: Implementing a Rating System for Restaurants

### ISSUE THREAD

**Issue by SrijaVuppala295** [VanshKing30/FoodiesWeb#123]
### Describe the feature

Implement a rating system for every restaurant listed on the platform.
Allow users to rate restaurants on a scale (e.g., 1 to 5 stars) .
Display aggregated ratings prominently on each restaurant's page.
Encourage user engagement by prompting users to leave ratings and reviews after visiting a restaurant.

### Add ScreenShots

![a10](https://github.com/VanshKing30/FoodiesWeb/assets/140592148/6d574c1e-3dca-4d2b-a652-5155d0603254)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Can you please explain me the approach to do or to add this feature ?

**Comment by SrijaVuppala295** [comment]
Yeah sure!! As we have the meal feadback for the every restaurant.We will add ratings also including the feedback.

![Screenshot 2024-05-14 141545](https://github.com/VanshKing30/FoodiesWeb/assets/140592148/78debd68-dda4-4345-8c42-d49f3738edf1)

**Comment by SrijaVuppala295** [comment]
Please assign it to me!!

**Comment by VanshKing30** [comment]
There's no point doing this !
