### ISSUE TITLE
BUG: [UI] Fix Canteen Section

### ISSUE THREAD

**Issue by TejasNasre** [VanshKing30/FoodiesWeb#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

After Canteen Login  User We Have Section For Add Breakfast And All Stuff But The Btn Are Cut With Header So I Want To Fix Small Ui Bug. 

In Mobile Screen the ui is good but not in desktop and medium screen.

![uibug](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/e5e3261d-0170-46fe-9c6c-2ffeadb2cd04)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Assigned you !! Raise PR when done
