### ISSUE TITLE
The about us section is not responsive 

### ISSUE THREAD

**Issue by sharmi4590** [VanshKing30/FoodiesWeb#129]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @VanshKing30 
The about us is not at all responsive. I will make it responsive and also will add some stylings to the card section in about us because it is taking so much space and it will not be user friendly if it occupies much space. Whole UI for the about section will be enhanced.
I am a GSSoC'24 contributor.
![Screenshot_20240514-212427](https://github.com/VanshKing30/FoodiesWeb/assets/102676949/9333b107-3f30-4054-ba5f-28501b835018)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Sorry !! Someone is alredy working on it !
