### ISSUE TITLE
Feature Request: Enhancing Website with Search Feature on Home Page and Hamburger Menu for Mobile Screen

### ISSUE THREAD

**Issue by unnihc369** [VanshKing30/FoodiesWeb#13]
Hi @VanshKing30,

I've identified an opportunity to enhance the website by adding a search feature to the home page and implementing a hamburger menu for improved navigation on mobile screens.

Expected behavior:
The website layout should adapt responsively to different screen sizes, ensuring that all elements, including the newly implemented search feature on the home page and the hamburger menu for mobile navigation, are easily accessible and displayed correctly on mobile devices.

Looking forward to contributing to the project under Gssoc'24!

**Comment by VanshKing30** [comment]
That Seems Like a good enhancement in the project , i am assigning this issue to you !! Make sure to create a pull request after solving or enhancing the feature.

**Comment by aman-kumar162** [comment]
hi even i want to work  on this feature the search bar in between the  logout and about us section should be look cool

**Comment by VanshKing30** [comment]
@aman-kumar162 How long will it take you to make changes in it ?

**Comment by unnihc369** [comment]
I can complete this in 2 days.
