### ISSUE TITLE
Feat: canteen user profile 

### ISSUE THREAD

**Issue by TejasNasre** [VanshKing30/FoodiesWeb#131]
### Describe the feature

As we know when we goes in the login as a canteen user and after  login we get in section page but we want to store canteen user profile and make a profile page for canteen user.

So I am implementing the backend for this to store the canteen user profile after making api for this i will intergrade with frontend as well it takes some time to implement.

### Add ScreenShots

canteen register page:
![logincanteen](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/a23aef3c-c2ae-4766-bb4b-ea50226918c7)

after login :
![fixcanteen](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/569130c4-2ef6-4892-b200-4cfb799a23d5)

But we did not make a profile page from user by which he can update the things and check the breakfast,lunch and dinner info.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TejasNasre** [comment]
please assign me this issue 😁

**Comment by VanshKing30** [comment]
Liked the solution , assigned you the issue
