### ISSUE TITLE
BUG: [UI] Brekfast, Lunch And Dinner Canteen Card Not Responsiveness 

### ISSUE THREAD

**Issue by TejasNasre** [VanshKing30/FoodiesWeb#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Breakfast, Lunch And Dinner Card Don't Have Responsiveness On Mobile Devices/Medium Screen: 

![Screenshot_2024-05-14-22-58-26-04](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/f2a3e3d8-1eb4-43a7-b391-1ae67986dd48)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TejasNasre** [comment]
I want to work on this issue.

**Comment by VanshKing30** [comment]
Assigned you this issue , Raise PR when done

**Comment by TejasNasre** [comment]
Yeah I have exam's but I will raise pr soon and after exams I will continue to this repo actively

**Comment by nishant0708** [comment]
assign me this issue under gssoc24

**Comment by TejasNasre** [comment]
raised the PR
