### ISSUE TITLE
BUG: Styling issue: Hover effect on 'Already have an account? Login' Link

### ISSUE THREAD

**Issue by Hannan2004** [VanshKing30/FoodiesWeb#135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hover effect on the 'Already have an account ? Login' link in the login/signup page causes the entire link to turn blue instead of just the login portion as intended. This might affect the user experience. We are just supposed to change the styling to solve the issue. I am a contributor in GSSOC 24 . I would request the project admins to please assign me the issue 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maryam-Sadaf** [comment]
@VanshKing30, I want to work on this issue please assign to me.
![Styling issue solution](https://github.com/VanshKing30/FoodiesWeb/assets/129180179/aee43202-9dc1-4f99-af32-de10545ab6ad)
