### ISSUE TITLE
Feat: Adding Hover effect in submit feedback button

### ISSUE THREAD

**Issue by AMISH-KHAN** [VanshKing30/FoodiesWeb#137]
### Describe the feature

submit feed back Button does not have hover effect we can add hover effect like it has in logout button

### Add ScreenShots

https://github.com/VanshKing30/FoodiesWeb/assets/123164129/b178a49d-d44d-4e21-9e56-d6ac5d3c7864

Please assign this issue to me under GSSoc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by narayani9120** [comment]
Kindly assign me these issues for GSSoC.

**Comment by VanshKing30** [comment]
@AMISH-KHAN Assigned you the issue, Raise the PR when done !!

**Comment by AMISH-KHAN** [comment]
@VanshKing30  I had some issues while setting up the backend.
 
![image](https://github.com/VanshKing30/FoodiesWeb/assets/123164129/31b70ddb-5772-43bb-81cc-f7781bf1aba6)

Although I solved it by self as it require to set up .env which will have DATABASE_URL="you mogodb address"
but I did not find it on Readme.md file. 

I can raise an issue regarding this and even solve this.
should I do it?

**Comment by AMISH-KHAN** [comment]
hey @VanshKing30  I kind of stuck here 😅

![image](https://github.com/VanshKing30/FoodiesWeb/assets/123164129/bc9b25fc-0a9c-40e5-97f6-7597074ac11a)

**Comment by harsh6045** [comment]
It would be great if you could assign me this issue..!
