### ISSUE TITLE
[New Feature] Adding a upload hotels image functionality for canteen owners

### ISSUE THREAD

**Issue by vivekrawat21** [VanshKing30/FoodiesWeb#14]
Objective:
Implement an email verification system for user registration and login processes to enhance security and user experience.

Key Features:
Custom hotel image upload functionality for canteen

After Sign-in as a canteen there should be a functionality so that  an owner can upload his/her hotel image.

How to do it :
You can use multer and cloudinary or any other cloud platform for implementing this feature .

**Comment by vivekrawat21** [comment]
assign  me  this issue

**Comment by nakshatravyas** [comment]
Hey, I want to contribute to this project. I am a MERN stack developer and I have done internship, worked on several projects and won hackathons as well. I can do upload image functionality.

Here's my linkedin profile : https://www.linkedin.com/in/nakshatravyas/
Github profile : https://github.com/nakshatravyas

**Comment by Yadavanurag13** [comment]
I have done an image upload on Cloudinary with the help of multer middleware, 
I'm interested to contribute, can u assign me this issue under GGSOC'24

**Comment by Tarun2605** [comment]
I am interested in resolving this issue. I have experience with Google OAuth 2.0, cloudinary and multer. Please assign this to me.

**Comment by VanshKing30** [comment]
Similar issue has alredy been raised , if he fails to do so , i will continue with this convo.
