### ISSUE TITLE
Feat: Confirm password field missing in the sign up form

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [VanshKing30/FoodiesWeb#140]
### Describe the feature

it is important to ask for both the password and a confirm password field in a signup form. 

The confirm password field helps prevent errors by ensuring the user has entered their intended password correctly. Typing mistakes are common, and without a confirmation field, users might accidentally set a password they didn't intend to, leading to login issues later.

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/139672976/7aedff36-ce9e-4a51-a238-bcf7d44ccdc7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
I am thinking to add , another email verification in signup page and i think there's no need to add this feat for now
