### ISSUE TITLE
BUG: Layout Error in About page.

### ISSUE THREAD

**Issue by Mayur-666** [VanshKing30/FoodiesWeb#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The about page's layout is overflowing in all the browsers.

![Screenshot (546)](https://github.com/VanshKing30/FoodiesWeb/assets/118804110/6e46888b-b4bb-4c72-bac9-25de4f14422e)
![Screenshot (547)](https://github.com/VanshKing30/FoodiesWeb/assets/118804110/0865a542-4f1e-4f2e-bd26-e7fb914a56ab)
![Screenshot (548)](https://github.com/VanshKing30/FoodiesWeb/assets/118804110/f37868a4-7d95-4ec4-b639-fbf4cc931bce)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Mayur-666** [comment]
@VanshKing30 Please assign me this issue.

**Comment by Mayur-666** [comment]
Hey @VanshKing30,

**Comment by VanshKing30** [comment]
@Mayur-666 Start working on it , raise the PR when done !!

**Comment by Saksham2k3s** [comment]
Hi @VanshKing30, 
If no one is working on this issue, could you please assign it to me?
