### ISSUE TITLE
Feat:Additon of User Profile Details

### ISSUE THREAD

**Issue by aritra-sarkar-42** [VanshKing30/FoodiesWeb#142]
### Describe the feature

In the website after login or signup it doesn't have a dynamic user profile section. Users will also be able to edit the profile details and change password if required.

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/144362932/963d4737-a506-4cd2-8ba6-1538fefa78f0)
this doesn't have a separate user section which can be added on the left-hand side which will open a new popup side tab from the left side where the user will be able to see account details and edit them by clicking on the pencil tool which will be added.

Please assign this issue to me @

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Explain me the approach , to do this , 
For this isuue to be solve you need to work on both frontend and backend both parts !!

**Comment by aritra-sarkar-42** [comment]
I will add a separate component ,add routing to it and do both the frontend and the backend for it. It will fetch the user details that were assigned during the signup process, and i will add the edit profile name and change password feature to it.

**Comment by Ansh-Garg22** [comment]
Hey @VanshKing30,

Please assign this issue to me. I have completed similar tasks in my projects. I can handle the backend for this, making it dynamic so that users can change their details by editing and view their profiles via routing by creating a separate page for that.

**Comment by nhyadav05** [comment]
assign me this issue under gssoc24
