### ISSUE TITLE
BUG: Same Canteen name displayed multiple times

### ISSUE THREAD

**Issue by TanayMaurya84** [VanshKing30/FoodiesWeb#144]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

Same canteen name appears multiple times in the canteen list. So, I want to fix this issue so that it is ensured that a canteen's name not appears more than once.
![Screenshot 2024-05-16 012249](https://github.com/VanshKing30/FoodiesWeb/assets/128279252/5aba398a-3979-4218-a064-12df8aad4cd7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maryam-Sadaf** [comment]
hi @VanshKing30 I have searched the existing issues.I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 contributor
 I want to work on this issue
please assign me

**Comment by VanshKing30** [comment]
@TanayMaurya84 & @Maryam-Sadaf Please explain me the approach for solving this issuue , the one with better solution will take the assignment !! Be quick !!

**Comment by TanayMaurya84** [comment]
@VanshKing30 
![foodies_data](https://github.com/VanshKing30/FoodiesWeb/assets/128279252/7e31181b-8dc6-485f-abd2-27176b2ffba7)

After getting data of all canteens from database as 'res', I will first store names of all canteens in a Set, which will help us in getting unique canteen names, and then send the data of those unique canteens for rendering in CanteenList as 'res2'.

**Comment by Maryam-Sadaf** [comment]
1. Fetch Data: Use the fetch API to retrieve canteen data from an
   endpoint.
   2. Extract Unique Names: Process the fetched data using a Set to extract
   unique canteen names.
   3. Render List: Use a React component to display the unique canteen
   names in a list.

import React, { useState, useEffect } from 'react';

const CanteenList = ({ canteenNames }) => (
  <ul>
    {canteenNames.map((name, index) => (
      <li key={index}>{name}</li>
    ))}
  </ul>
);

const Canteens = () => {
  const [canteenNames, setCanteenNames] = useState([]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const response = await fetch('your-api-endpoint'); // Replace
'your-api-endpoint' with the actual API endpoint
        const res = await response.json();

        // Extract unique canteen names
        const uniqueNamesSet = new Set();
        res.forEach(canteen => {
          uniqueNamesSet.add(canteen.name);
        });

        const uniqueNamesArray = Array.from(uniqueNamesSet);
        setCanteenNames(uniqueNamesArray);
      } catch (error) {
        console.error('Error fetching canteen data:', error);
      }
    };

    fetchData();
  }, []);

  return (
    <div>
      <h1>Unique Canteens</h1>
      <CanteenList canteenNames={canteenNames} />
    </div>
  );
};

export default Canteens;

**Comment by VanshKing30** [comment]
@Maryam-Sadaf Assigned you the issue , Raise the PR when done 
Keep reporting the progress on discord 
My id : Vansh5238
