### ISSUE TITLE
Improve Login Page with Passport.js and OAuth2 Google Sign-In

### ISSUE THREAD

**Issue by Evadshell** [VanshKing30/FoodiesWeb#15]
Description:
I propose enhancing the login functionality of the FoodiesWeb project by implementing Passport.js for authentication and integrating OAuth2 Google sign-in. This will improve security, usability, and convenience for users.

Proposed Changes:

Integrate Passport.js for authentication.
Implement OAuth2 Google sign-in.
Update the login page UI to accommodate the new authentication methods.
Provide documentation for developers on how to set up and configure the new authentication system.

Expected Benefits:

Enhanced security through standardized authentication mechanisms provided by Passport.js.
Improved user experience with the option for OAuth2 Google sign-in, reducing friction for new users.
Potential for increased user engagement and retention.

References:

[Passport.js Documentation](http://www.passportjs.org/)
[OAuth2 Google Sign-In Documentation](https://developers.google.com/identity/protocols/oauth2)

Additional Information:

I have previously implemented similar authentication features on my personal website ((https://secrets-phi.vercel.app/)), showcasing my experience with Passport.js and OAuth2 Google sign-in. I'm excited to contribute these skills to FoodiesWeb and enhance its authentication system.I assure you that while enhancing the login page, I'll ensure the backend logic remains consistent and functional. I'm excited to contribute these skills to FoodiesWeb and enhance its authentication system.

**Comment by Evadshell** [comment]
I am participating in GSSoC and I'm eager to contribute to the FoodiesWeb project. This issue aligns well with my skills and interests, and I would be thrilled to work on enhancing the login functionality with Passport.js and OAuth2 Google Sign-In. I kindly request the project maintainers @VanshKing30  to assign this issue to me so that I can begin working on it promptly. Thank you for considering my contribution.

**Comment by VanshKing30** [comment]
@Evadshell How long will it take to implement this task ??

**Comment by Evadshell** [comment]
Based on my experience implementing similar features across various web applications, I estimate that integrating the login functionality will only require a few hours of work. However, to ensure smooth implementation, I will need your cooperation in providing the necessary environment files and credentials.

Here's a breakdown of the steps I propose to take:


1. Utilizing Passport.js Package: I plan to incorporate the Passport.js npm package, leveraging its local strategy for username-password authentication. Additionally, I'll integrate Express-session for managing sessions and cookies, and implement Passport-strength to enforce password strength requirements (e.g., minimum 8 characters).
2. Enhancing Code Quality and Performance: Once the initial login feature is implemented, it will not only enhance the codebase but also improve performance while reducing the likelihood of errors. Following this, I intend to extend authentication capabilities by integrating Passport.js' Google strategy for seamless Google login. This will enable users to log in using their Google credentials, allowing us to access their email and profile information. I'll also update the navbar to display the user's profile photo obtained through Google login. For canteen staff, a separate Passport-local login strategy will be implemented.

3. Upon completing the login functionality, I'm eager to contribute further by addressing additional issues. One such enhancement would involve the implementation of a modal that appears immediately after user registration. This modal will contain a form allowing both customers and canteen staff to update their information seamlessly.

**Comment by ShreyashKathade** [comment]
can i work on that issue ?

**Comment by Tanu2205** [comment]
I hade experience of login authentication by using passport,I am glad to work on this issue.
Can you please assign me this issue under Gssoc'24?

**Comment by VanshKing30** [comment]
@Tanu2205 Please explain me your appraoch in dm 
My Discord id : Vansh5238
