### ISSUE TITLE
Feat: Missing User Profile Section After Login

### ISSUE THREAD

**Issue by ChandelAnish** [VanshKing30/FoodiesWeb#151]
### Describe the feature

Hello,

I would like to raise an issue regarding the absence of a user profile section after logging into the website. As a user, having a dedicated profile section is crucial for managing personal information, updating settings, and viewing account-related activities.

Steps to Reproduce:

Log in to the website using valid credentials.
Attempt to locate the user profile section.
Expected Result:
A user profile section should be accessible, allowing users to view and manage their personal information, settings, and account activities.

Actual Result:
There is no visible or accessible user profile section after logging in.

Impact:

Users are unable to update their personal information or preferences.
It hinders user experience and satisfaction.
Difficulty in managing account settings and viewing relevant user-specific information.
I would like to be assigned to this issue so I can work on implementing a user profile section that enhances the overall user experience.

Thank you.

### Add ScreenShots

![Screenshot 2024-05-16 150737](https://github.com/VanshKing30/FoodiesWeb/assets/123861376/1b4cd590-7aa8-4824-87f9-a9c65a8fa587)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ChandelAnish** [comment]
i would request to assign this issue to me under gssoc24
and also assign level(>2) to this issue

**Comment by ChandelAnish** [comment]
yeah I'll do please assign me this issue

**Comment by nishant0708** [comment]
assign me this issue under gssoc24
