### ISSUE TITLE
Feat: User can select their favourate food. The more the users choose it as favourite. the food will be upvoted and displayed to the canteen user.

### ISSUE THREAD

**Issue by Swastik19Nit** [VanshKing30/FoodiesWeb#153]
### Describe the feature

Creating a feature where users can select their favorite food and have it upvoted for display in the canteen is a great way to enhance user engagement and satisfaction.  This feature serves as a feedback mechanism for canteen management to gauge customer satisfaction in real-time.

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/122457803/195ab612-c9d5-42b6-85c7-e1fc09d9e8da)
a button can be added after each dish which on being clicked will get it upvoted.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
I think there's no need to add this feature right now !!
