### ISSUE TITLE
[Feature] : Login & signup page Ui

### ISSUE THREAD

**Issue by sivaprasath2004** [VanshKing30/FoodiesWeb#157]
### Describe the feature

- If i want to implement the `professional` login and signup page ui.
- It is more efficient for user attractive and user can make uses.
- i will work on this project to implement the Ui work and change the New Design.
- Please assign me..

### Add ScreenShots

![Screenshot from 2024-05-17 12-57-14](https://github.com/VanshKing30/FoodiesWeb/assets/121082414/b861433c-c0b4-446e-8cb8-101c3d5404a5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Share me the screen shots of changes you can make

**Comment by DevPatel1023** [comment]
@VanshKing30  Hey i am intersted to this project can you kindly share the discord channel for communication and discussion regarding to the project.

**Comment by Tejsvapandey1** [comment]
Hey @VanshKing30 i want to work on this issue

**Comment by zeba62** [comment]
Hey  @VanshKing30
I would really like to work on this.
Can you please assign this to me.
