### ISSUE TITLE
BUG: The buttons are overlapping with Navbar

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [VanshKing30/FoodiesWeb#158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When signing in as a canteen, the buttons (breakfast, lunch and dinner) are overlapping with the Navbar.

![gssoc6](https://github.com/VanshKing30/FoodiesWeb/assets/128472306/30a64fd7-6d17-41cd-83a1-056cb1914f53)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ayesha-Siddiqua88** [comment]
Hey @VanshKing30 , Please assign this issue to me.

**Comment by Maryam-Sadaf** [comment]
Hi @Vanshika-73, I have searched the existing issues please assign me.

**Comment by VanshKing30** [comment]
I have laredy assigned the same issue to someone else , thankyou for your concern , try finding another issue .
