### ISSUE TITLE
Feat: Adding Animation

### ISSUE THREAD

**Issue by harshmishra19** [VanshKing30/FoodiesWeb#161]
### Describe the feature

- Your about us page already looks fantastic, but incorporating animations on the images used could make it even more captivating. With my experience in this area, I'm eager to contribute to this enhancement.

### Add ScreenShots

FOR EXAMPLE

https://github.com/VanshKing30/FoodiesWeb/assets/115486960/554862ff-fed5-4908-89da-72c477b57182

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
This will make the website more buggy , alredy there exisit a lot of animations !!
