### ISSUE TITLE
Missing Footer in Website

### ISSUE THREAD

**Issue by Kavyasrikaki** [VanshKing30/FoodiesWeb#165]
### Describe the feature

The website currently does not have a footer section. Adding a footer can enhance user experience by providing additional navigation, contact information, or other relevant details.

Can you assign this issue to me under GSSOC24

### Add ScreenShots

![Screenshot 2024-05-18 153058](https://github.com/VanshKing30/FoodiesWeb/assets/143115964/e53f0637-0680-47c0-aef5-bb63ce3ce976)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Footer not needed right now !!
