### ISSUE TITLE
BUG: Missing 404 and 500 Error Pages

### ISSUE THREAD

**Issue by Kavyasrikaki** [VanshKing30/FoodiesWeb#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I noticed that the website currently does not handle 404 (Page Not Found) and 500 (Internal Server Error) errors. Adding custom error pages for these situations can improve user experience by providing helpful information when something goes wrong.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kavyasrikaki** [comment]
Can you assign this issue to me under GSSOC24 and also specify the level in contribution.

**Comment by shreyasupe35** [comment]
hi,I would like to work on this issuse

**Comment by Aryan01903** [comment]
hi i would like to contribute in this. please assign it to me

**Comment by VanshKing30** [comment]
Error 404 Page already exist !!
