### ISSUE TITLE
Feat: Home page UI improvemnet + add Home page data in separate navigation link

### ISSUE THREAD

**Issue by shivamgaur99** [VanshKing30/FoodiesWeb#167]
### Describe the feature

@VanshKing30  
We need to improve the home page UI by adding a carousel with images and moving the current list of hotel canteens to a separate page. This will enhance the visual appeal of the home page and make it more organized.
assign it to me under gssoc24

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/128178418/de71b68f-b03c-42a2-b324-8233783b9d94)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Cool I liked the feature , I looks very messy to see all the res. in one page
