### ISSUE TITLE
Typo in Toast Message

### ISSUE THREAD

**Issue by Disha-Hati** [VanshKing30/FoodiesWeb#17]
![image](https://github.com/VanshKing30/FoodiesWeb/assets/70029959/3d4f7904-a81a-4d52-83cd-dc581167e2b5)
It should be Create not craete.

I'm GSSOC'24 Contributor. Can you please assign this to me?

**Comment by VanshKing30** [comment]
Oh, nice observation skills! I didn't recognize it. I am assigning this task to you.

**Comment by VanshKing30** [comment]
@Disha-Hati Please Complete it very soon

**Comment by Disha-Hati** [comment]
@VanshKing30  Sure!

**Comment by Disha-Hati** [comment]
Hi, @VanshKing30 
Can you please check this?
![image](https://github.com/VanshKing30/FoodiesWeb/assets/70029959/3aa0762a-6103-488d-8f62-805a8a1646bd)
