### ISSUE TITLE
Feat: Floating button to scroll to top

### ISSUE THREAD

**Issue by Asymtode712** [VanshKing30/FoodiesWeb#173]
### Describe the feature

I wish to add a floating button which on clicked would scroll back to the top.

### Add ScreenShots

![float btn](https://github.com/VanshKing30/FoodiesWeb/assets/115717746/46211dcf-1d02-4096-b9be-ab64004a83cf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@VanshKing30 please assign me this issue under gssoc'24

**Comment by hustlerZzZ** [comment]
@Asymtode712 Assigning this issue to you
