### ISSUE TITLE
Feat: Disable Login and Signup Buttons While Fetching Data

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#174]
### Describe the feature

When the data is being fetched for the signup and login processes, the respective buttons should be disabled. Additionally, instead of displaying "Login" or "Signup," the buttons should display "Loading..." to enhance the user interface and user experience (UI/UX).

### Add ScreenShots

![add loader](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/b4b78615-e7d5-466c-8345-9b694e436039)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Hy @VanshKing30,
Please assign this issue to me under GSSOC'24

**Comment by hustlerZzZ** [comment]
@Saksham2k3s Great idea go ahead
