### ISSUE TITLE
BUG: About page images styling

### ISSUE THREAD

**Issue by The-Phoenics** [VanshKing30/FoodiesWeb#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @VanshKing30 ,
I've noticed with the window resize the images are getting squished, which doesn't look good. This could be solved with `object-fit` css property on the images. Also some other styling problem I would like to fix on about page. 

I played with CSS properties on the browser and here a little before and after:

## Current:
![about6](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/648ef655-394c-4bfe-bf99-95c23add5253)
![current](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/5f196ebe-9e44-4866-83ae-7c1272c7dfe0)

---

## Enchanced:
![about4](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/826563c5-f44f-4575-841b-f2aaab9aefeb)
![about1](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/bc9b4b2c-1ac7-4603-8633-510ebbf6ea62)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shivamgaur99** [comment]
@The-Phoenics bro you mention someone else

**Comment by The-Phoenics** [comment]
> @The-Phoenics bro you mention someone else

My bad 😅

@VanshKing30

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.
