### ISSUE TITLE
Unnecessary Re-Selection of User Type on Login

### ISSUE THREAD

**Issue by nightcoder26** [VanshKing30/FoodiesWeb#18]
## Unnecessary Selection of User Type on Login

**Issue Type:** Improvement Proposal

**Description:**

 Currently, upon login, users are presented with the option to choose between "Canteen" and "User" roles. Which is unnecessary to ask everytime they login as its decided at signup

**Expected Behavior:**

We should retain the user type decided during signup and automatically log the user in based on their role (Canteen or User) without asking them to choose again every time they login.

Actual Behavior:

Users are given the choice to login as user and canteen everytime they try to login 

**Possible Solutions:**

Implement logic to store the user type chosen during signup and automatically use it during login.

**Assign this issue to me. I can work on it**

**Comment by VanshKing30** [comment]
Given your expertise, I believe you're well-equipped to tackle this task effectively. If you have any questions or need clarification on any aspect of the issue, feel free to reach out. Your contribution to improving our system's user experience is highly valued.

Looking forward to your insights and progress on this.

Best regards,
Vansh

**Comment by agxmbedi** [comment]
I am Agamjot Singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by AmrutaZagade** [comment]
Hey @VanshKing30 i would like to work on this issue
