### ISSUE TITLE
Feat: Add back to top button 

### ISSUE THREAD

**Issue by Saimanjari777** [VanshKing30/FoodiesWeb#181]
### Describe the feature

The add to top button is missing which has smooth transition effect
I want to add the ack to top button which compliments the style of our website.
Please assign this task to me @va

### Add ScreenShots

![Screenshot 2024-05-18 223103](https://github.com/VanshKing30/FoodiesWeb/assets/130165687/e1ccf78a-f93e-433f-926c-6eecfcdb3813)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Someone is already working on it..

**Comment by Saimanjari777** [comment]
Can u please check once. I think I have raised this issue first @hustlerZzZ

**Comment by hustlerZzZ** [comment]
@Saimanjari777 You can check #173
