### ISSUE TITLE
Feat: Displaying Error Message from Backend in Toast Notification

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#182]
### Describe the feature

Currently, the application makes an API call using Axios to create an account. On a successful response, a success toast message is shown, and the user is navigated to the home page. However, when an error occurs, a hard-coded error message (Failed To create account) is displayed in every case. I want to display the error message received from the backend in the toast notification instead of the hard-coded message.

### Add ScreenShots

![Hardcoded](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/a56bf01d-4040-49aa-87f6-c9d48750d974)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
@VanshKing30 Please assign this issue to me under GSSOC'24

**Comment by Abhinav-Sharma06** [comment]
@VanshKing30 @Saksham2k3s please assign me this task under GSSOC 2024. I am confident that I can fix this task

**Comment by hustlerZzZ** [comment]
This will expose major backend errors. You have to check if any unsuccessful call doesn't leak any type of backend data!
@Saksham2k3s

**Comment by Taranpreet10451** [comment]
Can you please assign this to me.

**Comment by hustlerZzZ** [comment]
> Can you please assign this to me.

How are you going to proceed?

**Comment by hustlerZzZ** [comment]
> I will use a toast notification library like "react-toastify" or any other you are using to display the error message.

This will expose major backend errors. You have to check if any unsuccessful call doesn't leak any type of backend data!

**Comment by Taranpreet10451** [comment]
1.We handle different types of HTTP error status codes separately.
2.For common errors like bad requests, unauthorized access, and resource not found, we provide generic error messages to the client without exposing detailed backend information.
3. For other types of errors where there's no response from the server or if there's an unexpected error, we provide a generic error message as well.
