### ISSUE TITLE
Feat: News Card default image

### ISSUE THREAD

**Issue by ANI2707** [VanshKing30/FoodiesWeb#183]
### Describe the feature

 There should be default image provided for news cards if the API does not supply any images

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/108017771/b3e2e1aa-b50a-4feb-bd8c-812e66182361)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ANI2707** [comment]
@VanshKing30 please assign this issue to me.

**Comment by hustlerZzZ** [comment]
@ANI2707 Kindly proceed!

**Comment by ANI2707** [comment]
@hustlerZzZ   what is the default REACT_APP_DEFAULT_QUERY string

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ   what is the default REACT_APP_DEFAULT_QUERY string 

Can you share the screenshot

**Comment by ANI2707** [comment]
> > @hustlerZzZ   what is the default REACT_APP_DEFAULT_QUERY string
> 
> Can you share the screenshot
![Screenshot (790)](https://github.com/VanshKing30/FoodiesWeb/assets/108017771/112da38c-5e0b-469b-a4ce-056ef50e5502)

**Comment by ANI2707** [comment]
@hustlerZzZ 
![Screenshot (790)](https://github.com/VanshKing30/FoodiesWeb/assets/108017771/65c11954-f9fa-4d4a-9b93-4177b808d800)

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ 
> ![Screenshot (790)](https://github.com/VanshKing30/FoodiesWeb/assets/108017771/65c11954-f9fa-4d4a-9b93-4177b808d800)
> 

What's the error

**Comment by ANI2707** [comment]
@hustlerZzZ By mistake I put  .env file in the src folder instead of root folder . It's working now

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ By mistake I put  .env file in the src folder instead of root folder . It's working now

Ok

**Comment by ANI2707** [comment]
@hustlerZzZ what default image should I add?

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ what default image should I add?
> 

You can fetch some random news images from some api
