### ISSUE TITLE
Feat: Automate greeting using Github bot 🤖

### ISSUE THREAD

**Issue by shubhammjha22** [VanshKing30/FoodiesWeb#185]
### Describe the feature

As the contributor count rises on the repo, it becomes increasingly challenging for maintainers to personally greet and encourage each contributor for their valuable input. Equally important is the reminder for them to review the project's contribution guidelines.

I would like to add a github bot , which would greet the user whenever there is a PR request or a issue raised
with something like

For PR
"Awesome work, @username! 🎉 Thank you for submitting pull request.
We truly appreciate your contribution and efforts to enhance our project.
Please ensure that you have followed the contributing guidelines for a smooth review process"

For Issue
"Hello @userName,
Thanks for creating this issue and contributing to Tourism!
@admin will review your issue soon and provide feedback. In the meantime, feel free to join the discord community. Please ensure that you have followed the contributing guidelines for a smooth review process"

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/68507333/82315c92-5c2f-4b82-b8a2-2efd52a084c3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shubhammjha22** [comment]
@VanshKing30  Please Assign this issue to me , i would like to work on this under GSSoC'24

**Comment by hustlerZzZ** [comment]
Hey, @shubhammjha22 this is a great addon for our project. Kindly proceed!

**Comment by shubhammjha22** [comment]
@hustlerZzZ i have made the PR kindly review it , and also add the Labels in the PR as per the guidelines .
Thank you
