### ISSUE TITLE
Redesign README Image

### ISSUE THREAD

**Issue by me-shweta** [VanshKing30/FoodiesWeb#187]
### Describe the feature

@VanshKing30  I am Shweta. As part of GSSOC'24, I'm keen on redesigning the image for FoodiesWeb to make it more visually appealing. Assign me this task! 

### Add ScreenShots

**Referenced Image** ( The image I am talking about )
<img width="195" alt="2" src="https://github.com/VanshKing30/FoodiesWeb/assets/119609866/b2146acb-6be9-4b8c-b5c2-29c9d5ae2d58">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by me-shweta** [comment]
@VanshKing30 is there any update ?

**Comment by me-shweta** [comment]
@VanshKing30 ?

**Comment by hustlerZzZ** [comment]
Yeah you can do that... @me-shweta

**Comment by me-shweta** [comment]
**@hustlerZzZ I have created some designs. Here they are.**
![1](https://github.com/VanshKing30/FoodiesWeb/assets/119609866/821312ed-8797-42c5-a04c-ba5fb5e85664)
![2](https://github.com/VanshKing30/FoodiesWeb/assets/119609866/5e5202a7-b97c-4232-a1c8-53448c700009)
![3](https://github.com/VanshKing30/FoodiesWeb/assets/119609866/075cb8cd-59f6-4f4f-b0ae-91532adbe283)
![4](https://github.com/VanshKing30/FoodiesWeb/assets/119609866/96257bc4-8327-4df1-9429-6523e6c520d2)
**Let me know which design suits you best and if there are any changes you would like to make.
Is there any tagline for FoodiesWeb?**

**Comment by 143divya** [comment]
Can you please assign this issue to me. l want to work on this

**Comment by me-shweta** [comment]
@hustlerZzZ waiting for your response

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ waiting for your response

Sorry for the delay!
First one is looking amazing!

**Comment by me-shweta** [comment]
should I proceed with the pr ? @hustlerZzZ

**Comment by hustlerZzZ** [comment]
> should I proceed with the pr ? @hustlerZzZ

sure

**Comment by me-shweta** [comment]
@hustlerZzZ By the way, don't forget to add me as an assignee and add a label to the PR, like this issue. This way, it will be included in the GGSOC contribution.
