### ISSUE TITLE
Auto Commenting when a PR is merged

### ISSUE THREAD

**Issue by suhanipaliwal** [VanshKing30/FoodiesWeb#193]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by hustlerZzZ** [comment]
Issue for this is already raised..
Issue #185

**Comment by suhanipaliwal** [comment]
> Issue for this is already raised.. Issue #185

That issue is adding a greeting bot which will comment when a new issue or pr is made. But I will be adding the feature of auto commenting after a pull request is merged by the maintainers. Both issues are different.

**Comment by hustlerZzZ** [comment]
Oh Okay, I got the wrong idea... Assigning this issue to you,....
