### ISSUE TITLE
BUG: About Link in Footer doesn't Scrolls Up on Click

### ISSUE THREAD

**Issue by Amruta7203** [VanshKing30/FoodiesWeb#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Clicking on the About link in the footer opens the About page, but the page doesn't scroll to the top. This results in the footer still being visible above the About page content.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Can you attach an image as well...

**Comment by Amruta7203** [comment]
Hello @hustlerZzZ.  Signing in the website is showing some error so I can't share the recording. But what I mean by raising the issue is that the about link in the footer is not functioning. 
Expected: About link clicked should scroll up to the About section.
