### ISSUE TITLE
BUG: Unnecessary white spaces on the About page

### ISSUE THREAD

**Issue by Amruta7203** [VanshKing30/FoodiesWeb#197]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is unnecessary space between components on the About page. These spaces need to be eliminated for a better user experience.

![image](https://github.com/VanshKing30/FoodiesWeb/assets/116087736/bffaf558-07c2-4932-b1ed-b90ab6a9b91d)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/116087736/e2d0eef3-ef53-497e-8f8a-9d6f4249303b)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/116087736/ef7facb4-3d34-4dae-aea0-d62723e6a27e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
@Amruta7203 Kindly proceed! Assigning this issue to you...

**Comment by 143divya** [comment]
Please assign this issue to me under Gssoc24

**Comment by hustlerZzZ** [comment]
> Please assign this issue to me under Gssoc24

Ok start working on it.

**Comment by Amruta7203** [comment]
I'm already working on it @hustlerZzZ
