### ISSUE TITLE
Feat: Auto Commenting when an Issue is Closed

### ISSUE THREAD

**Issue by Asymtode712** [VanshKing30/FoodiesWeb#198]
### Describe the feature

This feature aims to solve the problem of poor communication and lack of acknowledgment when issues are closed. By automatically commenting on closed issues, it ensures that contributors are informed about the closure and are thanked for their efforts. This helps maintain a positive and engaging community atmosphere, encouraging continued contributions and fostering good relationships between maintainers and contributors.

### Add ScreenShots

![issue closed](https://github.com/VanshKing30/FoodiesWeb/assets/115717746/0f4a1706-4ad7-4153-8200-9334de12f63d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@VanshKing30 please assign me this issue

**Comment by hustlerZzZ** [comment]
The issue is already raised...
Issue #185

**Comment by Asymtode712** [comment]
@hustlerZzZ #185 Only comments on Issue creation and PR Raised, this workflow comments when an issue is closed

**Comment by hustlerZzZ** [comment]
@Asymtode712 My bad, Too many issues got confused... 
Assigning this issue to you!

**Comment by Asymtode712** [comment]
@hustlerZzZ No problem, will raise a PR for this issue soon

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ No problem, will raise a PR for this issue soon

Sure
