### ISSUE TITLE
Feat: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [VanshKing30/FoodiesWeb#199]
### Describe the feature

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Add ScreenShots

![Close Old Iss](https://github.com/VanshKing30/FoodiesWeb/assets/115717746/ea579c8f-b6fd-454d-962a-b6c3be0fc64e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@VanshKing30 please assign me this issue

**Comment by hustlerZzZ** [comment]
How are you going to do this.. Explain more....

**Comment by Asymtode712** [comment]
@hustlerZzZ So basically what this proposed workflow will do is, it would first determines those issues which were inactive for a span of 30 days or more and then it would close them as a result of inactivity for almost a month, if you say I can change the time span after which an issue is to be closed

**Comment by hustlerZzZ** [comment]
Okay got your point 

> @hustlerZzZ So basically what this proposed workflow will do is, it would first determines those issues which were inactive for a span of 30 days or more and then it would close them as a result of inactivity for almost a month, if you say I can change the time span after which an issue is to be closed

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ If you are satisfied with this feature and want me to work on this then please assign me this issue
> 
> Thank you!

Done
