### ISSUE TITLE
I have hosted the backend on Render , but due to inactivity the website has a delay , any solutions to this ?? 

### ISSUE THREAD

**Issue by VanshKing30** [VanshKing30/FoodiesWeb#20]

**Comment by TejasNasre** [comment]
yeah i have many website  that i hosted on render including backend but the render as sleep time after 30 - 60 min of inactive so the application get roll off and takes 60 - 120 seconds to roll on. So don't deploy backend on render use vercel.vercel is best for backend deployment both backend and frontend.So Vercel is best.

**Comment by powerstone666** [comment]
or you can create an automated script that not only hits your current but all of your repositories API after a certain amount decided by you.

**Comment by TejasNasre** [comment]
I think writing script for Vercel is great but if you deploy the backend on Vercel the deployment get automatically when the main branch /server get update no need to write script it's easy.correct me if I am wrong.

**Comment by SumitKumar-17** [comment]
You could host the backend on vercel ,and complete it by creating a vercel.json file then it gets automatically deployed as soon as you update your hosted dev branch.

**Comment by Tushtiadlakha** [comment]
assign this issue to me under gssoc'24 @Tushtiadlakha . I have faced the same issue, i can fix it on render itself. We can use something like uptime bot.
