### ISSUE TITLE
Feat: Workflow for closing Old PRs

### ISSUE THREAD

**Issue by Asymtode712** [VanshKing30/FoodiesWeb#200]
### Describe the feature

This feature aims to automate the management of open PRs in a repository, ensuring that outdated or abandoned PRs are closed in a timely manner. By doing so, it helps maintain repository hygiene, improves workflow efficiency, and provides a better experience for both maintainers and contributors.

### Add ScreenShots

![Close Old PRs](https://github.com/VanshKing30/FoodiesWeb/assets/115717746/c4e2f1d4-3f9c-418a-b17d-ff1668c7989b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@VanshKing30 please assign me this issue

**Comment by Asymtode712** [comment]
@hustlerZzZ Is this feature not required for now??

**Comment by hustlerZzZ** [comment]
By mistake you create two issues @Asymtode712

**Comment by Asymtode712** [comment]
@hustlerZzZ No, the previous issues was for closing old `issues` this is for closing old `PRs`

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ No, the previous issue was for closing old `issues` this is for closing old `PRs`

😢 My badddddd

**Comment by hustlerZzZ** [comment]
Check now!!
