### ISSUE TITLE
Feat: add back to top button

### ISSUE THREAD

**Issue by prachita0504** [VanshKing30/FoodiesWeb#206]
### Describe the feature

back to top helps user to directly jump into the home page

### Add ScreenShots

![Screenshot 2024-05-26 230418](https://github.com/VanshKing30/FoodiesWeb/assets/139040702/188036d2-5a0a-4471-88f7-9da2dd5eb2d6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
@prachita0504 Issue #205 is already created. Kindly check that. You can contribute there.
