### ISSUE TITLE
Feat: Forgot password feature.

### ISSUE THREAD

**Issue by sharmi4590** [VanshKing30/FoodiesWeb#207]
### Describe the feature

In sign in , adding forgot password feature or create a new password feature will enhance the user experience .

### Add ScreenShots

![Screenshot (478)](https://github.com/VanshKing30/FoodiesWeb/assets/102676949/cb075728-dc2a-4fc1-b9b0-7a9e7b4c8625)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Adityajparmar37** [comment]
The repo Owner has not giving mongo db  uri then how to do it ?

**Comment by Taranpreet10451** [comment]
Please assign this to me.

**Comment by hustlerZzZ** [comment]
@sharmi4590 how are you going to do this.. Sending JWT token via email ??

**Comment by Chandan-6** [comment]
Please assign this issue to me under GSSoC24

**Comment by Adityajparmar37** [comment]
> @sharmi4590 how are you going to do this.. Sending JWT token via email ??

Yess sending link with token and if token is correct for specific time then allow to reset password otherwise not

**Comment by hustlerZzZ** [comment]
> > @sharmi4590 how are you going to do this.. Sending JWT token via email ??
> 
> Yess sending link with token and if token is correct for specific time then allow to reset password otherwise not

Okay, start working on it. I am assigning this issue to you..
