### ISSUE TITLE
Update README for Improved Contributor Guidelines

### ISSUE THREAD

**Issue by Evadshell** [VanshKing30/FoodiesWeb#21]
Description:
The current README of the FoodiesWeb project lacks clear instructions for contributors, particularly regarding setting up and running the server. Currently, users need to navigate to the server directory, run npm i, and then run nodemon server.js. This process can be confusing, especially for new contributors. We need to update the README to provide clear, step-by-step instructions for setting up and running the server, possibly utilizing split terminals for better clarity.

Proposed Changes:

Revise the contributor guidelines section in the README to include clear instructions for setting up and running the server.
Provide step-by-step instructions, including navigating to the server directory, installing dependencies with npm i, and running the server with nodemon server.js.
Consider suggesting the use of split terminals for better organization and clarity during the setup process.

Expected Benefits:

-Improved onboarding experience for new contributors.
-Reduced confusion and errors during the setup and running of the server.
-Increased efficiency in development workflows.

**Comment by Evadshell** [comment]
please assign this issue to me @VanshKing30 i will fix this asap

**Comment by VanshKing30** [comment]
@Evadshell, I'm assigning you this issue. Please solve it and create a pull request. Thanks!

**Comment by Evadshell** [comment]
please check sir i've updated it!
