### ISSUE TITLE
BUG: SignUp and SignIn not working 

### ISSUE THREAD

**Issue by SamarthUrane** [VanshKing30/FoodiesWeb#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I am not able to create account.  It is showing failed to create account. I can fix this issue.
Please assign me this issue under GSSOC'24.
![image](https://github.com/VanshKing30/FoodiesWeb/assets/108013711/cc08af88-a4fc-430b-82b8-c71fab9d7f19)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iamrudhresh** [comment]
Hey, hope you're doing great! As an GSSoC contributor, I'm keen on ramping up my involvement for GSSoC'24. Could you assign this issue to me? I'm excited to continue contributing to the project. Thanks a bunch!!
