### ISSUE TITLE
BUG: Local api is running for student signup

### ISSUE THREAD

**Issue by Samani-Humaira** [VanshKing30/FoodiesWeb#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When trying to signup local api is running

![image](https://github.com/VanshKing30/FoodiesWeb/assets/142516438/94f40c1f-c55c-4b93-b7ec-3b2af035a734)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Issue already raised about this..
#213
