### ISSUE TITLE
BUG: News page UI

### ISSUE THREAD

**Issue by The-Phoenics** [VanshKing30/FoodiesWeb#219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The content section of the news page is not center aligned and has excess top-margin. The title should have some top margin as well.
This could be solved by adding flex to the parent-container and properly horizontally aligning the children of container.

![bug-news-page](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/5d4a66ad-4e90-4bab-9472-816b2ea3c6bf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by The-Phoenics** [comment]
Hey @hustlerZzZ 
I would like to work on this for GSSoC'24. Can you assign this to me?

**Comment by hustlerZzZ** [comment]
@The-Phoenics Go ahead.

**Comment by The-Phoenics** [comment]
Hey @hustlerZzZ
I am having some issue setting up project's backend which is not working for me. And I could not find any instruction on setting it up.

![console](https://gi
![browser](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/a2230c40-3616-4405-aac6-fc6b540c92f6)
thub.com/VanshKing30/FoodiesWeb/assets/96228962/4020086b-6fa8-4a79-aacc-c73852ce823a)

Is there anything I am missing that would resolve these errors?

**Comment by hustlerZzZ** [comment]
> Hey @hustlerZzZ I am having some issue setting up project's backend which is not working for me. And I could not find any instruction on setting it up.
> 
> ![browser](https://private-user-images.githubusercontent.com/96228962/336336519-30b2e9d4-871b-4737-95ba-3aa236e7e2ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODQzMDAsIm5iZiI6MTcxNzQ4NDAwMCwicGF0aCI6Ii85NjIyODk2Mi8zMzYzMzY1MTktMzBiMmU5ZDQtODcxYi00NzM3LTk1YmEtM2FhMjM2ZTdlMmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2NTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMTQxZDJiMGY5NTI3MGM2N2NlYWM3NmNjZjgyMDM0ZGNkODVhM2M1YWI3N2I4YzEyNzBjYmZkNTZiYTEyOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a0YORcRz-KJSbg4Bo9R-7ufHIzrZlILw_ivrxWCsH7o) ![console](https://private-user-images.githubusercontent.com/96228962/336336531-c62500ee-9c2b-4012-978f-877bef26df71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODQzMDAsIm5iZiI6MTcxNzQ4NDAwMCwicGF0aCI6Ii85NjIyODk2Mi8zMzYzMzY1MzEtYzYyNTAwZWUtOWMyYi00MDEyLTk3OGYtODc3YmVmMjZkZjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA2NTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZjdlYmQzZGQxOWJlZDQzNDRjOWQ2Mjk5OTYwYmY2MGNlMDVhYWIyNjQ0YzFlMzdmNmI2ZGFkZjEzNzg4YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wlFIXewThcmWzdEMZmd2U91pz1ZkeJ0D8pjN5fB5BGM)
> 
> Is there anything I'm missing that would resolve these errors?

Let me check

**Comment by hustlerZzZ** [comment]
@The-Phoenics try using local mongodb instance

**Comment by The-Phoenics** [comment]
@hustlerZzZ  I've connected it to my localhost mongodb instance. But there is not news data in there. 
![backend](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/34de1b37-02a7-47e9-ae1b-f56be3f9c3e2)

So, how can I work on the UI without new data element?
![news](https://github.com/VanshKing30/FoodiesWeb/assets/96228962/d406757d-071e-40fd-b3c6-8c5438e2b21c)

**Comment by hustlerZzZ** [comment]
Add some data in your instance
