### ISSUE TITLE
Feat:adding blog section

### ISSUE THREAD

**Issue by ksatya2003** [VanshKing30/FoodiesWeb#225]
### Describe the feature

In this blog section we upload image and description about image that is very helpful to easily understand about dishes

### Add ScreenShots

https://restaurant.eatapp.co/hs-fs/hubfs/Best-restaurant-website-design-inspirations_4_michiramen-3%20(1).jpg?width=1024&name=Best-restaurant-website-design-inspirations_4_michiramen-3%20(1).jpg

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Not getting your point...

**Comment by ksatya2003** [comment]
JusT add important news about dishes

**Comment by hustlerZzZ** [comment]
> JusT add important news about dishes

let me ask other mentor's

**Comment by hustlerZzZ** [comment]
@VanshKing30 @mrigankabrahma does we need this ?
