### ISSUE TITLE
BUG: Redesign the Menu Button for Better UI

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current menu button design could be improved to provide a better user interface and user experience. The button's appearance should be more intuitive and visually appealing to enhance navigation.
![menu-btn](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/4685d49c-acf0-466c-95b4-3bac77809835)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Hi @hustlerZzZ,
Please assign this issue to me!

**Comment by hustlerZzZ** [comment]
> Hi @hustlerZzZ, Please assign this issue to me!

Ok go ahead

**Comment by Saksham2k3s** [comment]
@hustlerZzZ  you have not added the GSSOC label to the issue! Will it not count for GSSOC?
