### ISSUE TITLE
Feat:Want To Add Backend Canteen menu item

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#232]
### Describe the feature

Currently  cateen cant add items in their menu 
![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/fc66c917-4a7b-4080-9fd1-32037a8ee319)
i want to implement its backend i will redesign this form here canteen will have to add name image and availablity time and rest of the fields which will be stored under that canteen id's menu and then we can fetch it using user's end .

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/487a591f-47df-4083-b564-d0a618a7953e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Can you explain more...

**Comment by nishant0708** [comment]
See the functionality we needed is whenever canteen adds  menu item from here means canteen end the user end should able to see the item that was added by canteen 

For that what we can do is write a post API which will take data from the form give here and it will be stored in  a database of that particular restraunt uid . When this data is stored in that uid 

In user section we can retrieve that information we will get array of items in that canteen an we can show that .

This is the basic idea which I will try to solve.and if this is done we can do further implementations like user can give order to canteen that he wants that particular item and so onn..
