### ISSUE TITLE
BUG: Navbar is overlapping the Heading of the News Page

### ISSUE THREAD

**Issue by the-code-artist** [VanshKing30/FoodiesWeb#239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

hey @hustlerZzZ
Navbar is overlapping the Heading of the News Page ("Trending Food and Health News")
![image](https://github.com/VanshKing30/FoodiesWeb/assets/115625321/e66404d9-9fbe-481c-ab45-46d012994bf2)
I would like to address this issue and make sure that the elements are properly aligned
please assign me this issue under GSSOC'24 !!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok go ahead, and fix that

**Comment by NalinDalal** [comment]
i would also like to work on same issue, if you could assign me
