### ISSUE TITLE
Feat: Contact us frontend 

### ISSUE THREAD

**Issue by Isha1233** [VanshKing30/FoodiesWeb#249]
### Describe the feature

Adding contact us frontend using React and styling it using tailwind CSS 

### Add ScreenShots

After implementation I will add

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Isha1233** [comment]
@VanshKing30 please assign this issue to me

**Comment by hustlerZzZ** [comment]
> @VanshKing30 please assign this issue to me

OK, Start working on this.. Assigning this issue to you.
