### ISSUE TITLE
Feat:contact us backend functionality

### ISSUE THREAD

**Issue by Isha1233** [VanshKing30/FoodiesWeb#250]
### Describe the feature

implementing it using node js and and contact directly send to via mail

### Add ScreenShots

After implementation I will add

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Isha1233** [comment]
@VanshKing30 kindly assign this issue to me

**Comment by hustlerZzZ** [comment]
> @VanshKing30 kindly assign this issue to me

Ok start working on this..

**Comment by sailaja-adapa** [comment]
@Isha1233 When i am trying to signup always saying can't sign up then how to view website can u please explain i would like to work on this project
