### ISSUE TITLE
BUG: Can't Signup

### ISSUE THREAD

**Issue by aayushchugh** [VanshKing30/FoodiesWeb#255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I tried signing up but It gives an error ( you can check in the network tab)

The API URL is wrong as it is pointing to the localhost but It should be pointed to the API deployed on production

<img width="1440" alt="image" src="https://github.com/VanshKing30/FoodiesWeb/assets/69336518/920abf88-443d-47d8-910c-95cf1d506d82">

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, Assigning this issue to you...

**Comment by aayushchugh** [comment]
@hustlerZzZ you have to update the `environment variables` in Vercel to solve this

**Comment by anuragnegi000** [comment]
@hustlerZzZ no environment variables needed to change in vercel it's just a small bug assign it to me
in localhost i have figured it out

**Comment by aayushchugh** [comment]
@anuragnegi000 you can pick this up :)

**Comment by anuragnegi000** [comment]
@aayushchugh thanks

**Comment by hustlerZzZ** [comment]
> @aayushchugh thanks

ok

**Comment by aayushchugh** [comment]
Still not able to signup and login

<img width="613" alt="image" src="https://github.com/VanshKing30/FoodiesWeb/assets/69336518/6c134c6c-74ca-4578-86f6-7b32253a3c0a">

<img width="617" alt="image" src="https://github.com/VanshKing30/FoodiesWeb/assets/69336518/a83f2f1d-3e63-43e5-9e6d-9d0d81409c18">

**Comment by anuragnegi000** [comment]
@aayushchugh if you're on localhost so add JWT_SECRET in .env file

**Comment by anuragnegi000** [comment]
There's a line missing in Readme.MD that add JWT_SECRET in .env

**Comment by aayushchugh** [comment]
@anuragnegi000 I tried this on production, not localhost

<img width="1439" alt="image" src="https://github.com/VanshKing30/FoodiesWeb/assets/69336518/cf2e2360-37f4-472f-8209-55838357db79">

**Comment by anuragnegi000** [comment]
but i'm able to login/signup

**Comment by aayushchugh** [comment]
are you trying on localhost?

**Comment by anuragnegi000** [comment]
@aayushchugh make sure you're not registering with same mail, that you may have registered previously

**Comment by aayushchugh** [comment]
Is your API server running on your localhost? stop the server on localhost and retry on production

**Comment by aayushchugh** [comment]
> @aayushchugh make sure you're not registering with same mail, that you may have registered previously

I am trying with a completely new email

**Comment by anuragnegi000** [comment]
@aayushchugh Yes ofcourse

**Comment by anuragnegi000** [comment]
> Is your API server running on your localhost? stop the server on localhost and retry on production

Yes ofcourse

**Comment by aayushchugh** [comment]
@anuragnegi000  Stop your server running on your localhost and try creating an account in production

**Comment by anuragnegi000** [comment]
@aayushchugh the backend is not hosted so it will not work

**Comment by anuragnegi000** [comment]
@aayushchugh check their .env files they haven't hosted

**Comment by aayushchugh** [comment]
@anuragnegi000 The backend is hosted here `https://foodiesbackend-yn7r.onrender.com/api/v1/`

**Comment by anuragnegi000** [comment]
Then this should be a separate issue i guess

**Comment by aayushchugh** [comment]
I raised this issue due to that URL problem only 😅

**Comment by aayushchugh** [comment]
@anuragnegi000 make the changes that I mentioned in PR and it should solve it.

**Comment by anuragnegi000** [comment]
someone changed the localhost:3000 to localhost:8000 and after changing, it's working fine for localhost

**Comment by aayushchugh** [comment]
The issue is that if the URL is set to `localhost` then the production will also try to make API calls to my `localhost` but I don't have the API server running so API calls will fail. Now instead of hardcoding, if we get the API URL from `.env` file then API calls will be made to the hosted backend instead of my `localhost`

**Comment by anuragnegi000** [comment]
check comments of #234 i took reference of localhost that's why worked for that only
but as per your issue i'll create for hosted URL too

**Comment by aayushchugh** [comment]
Take reference form this [pr](https://github.com/VanshKing30/FoodiesWeb/pull/273/files#diff-82e14b2512f569278e049de0c5e56e90ce95700ccb45e849abe33d6fa482a2bfR26-R27)

**Comment by anuragnegi000** [comment]
got it

**Comment by aayushchugh** [comment]
The thing is, `API` should take the URL from`.env` file instead of hardcoding because someone might run their backend server on `:8000` someone might do it on `:5000` so the best will be if we take URL from `.env` then everyone can just edit the port in their `.env` file only

**Comment by anuragnegi000** [comment]
yes thanks for reference and explanation

**Comment by anuragnegi000** [comment]
BTW from where did you found hosted backend URL

**Comment by aayushchugh** [comment]
@anuragnegi000 check this issue and you will know #256 😂

**Comment by anuragnegi000** [comment]
lol got it 😆
