### ISSUE TITLE
:lock: Security concern with `.env` file

### ISSUE THREAD

**Issue by aayushchugh** [VanshKing30/FoodiesWeb#256]
`ENV FILE`'s URL is logged in the console. This is a security concern because if someone puts sensitive data in the `.env` file, anyone can access it from the link logged in the console

I would like to work on this and get the link removed

<img width="617" alt="image" src="https://github.com/VanshKing30/FoodiesWeb/assets/69336518/fcd0ea4c-1300-4caf-8e67-2b6635847549">

**Comment by hustlerZzZ** [comment]
You can remove that..
