### ISSUE TITLE
ci: 👷🏼 greetings workflow failed on the main branch

### ISSUE THREAD

**Issue by aayushchugh** [VanshKing30/FoodiesWeb#257]
<img width="1068" alt="image" src="https://github.com/VanshKing30/FoodiesWeb/assets/69336518/8a92e484-82b2-4f0f-b2fa-8143375c4f2f">

**Comment by hustlerZzZ** [comment]
How are you going to fix that ?

**Comment by aayushchugh** [comment]
Not sure if I can fix this or not but I can try

**Comment by hustlerZzZ** [comment]
> Not sure if I can fix this or not but I can try

ok go ahead

**Comment by aayushchugh** [comment]
@hustlerZzZ there are two problems:

1. Github doesn't allow secrets to start with`GITHUB_` but our token is named `GITHUB_TOKEN`. We can rename this to `GH_TOKEN`
2. The token might not have the proper access to issues of this repository

I renamed the token and tried it on my repository and it is working fine.

Raising a PR to rename the token

![image](https://github.com/VanshKing30/FoodiesWeb/assets/69336518/618baa0a-706f-4457-b311-3b220002f3fc)
