### ISSUE TITLE
BUG:  Show Password Icon in Password Field Is Not Vertically Centered

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The "show password" icon in the password field is not vertically centered, causing misalignment and affecting the overall user experience. This issue needs to be addressed to ensure the icon is properly aligned in the center of the password field.

![show-icon](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/758258ab-40e9-47f5-b069-b8c55a747535)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, fix that
