### ISSUE TITLE
Add footer to the website

### ISSUE THREAD

**Issue by nagalakshmi08** [VanshKing30/FoodiesWeb#26]
![Screenshot 2024-05-10 201807](https://github.com/VanshKing30/FoodiesWeb/assets/121669832/b9c6f298-bfce-45b9-a080-04dacd1bb201)

Hi @VanshKing30 , It would be good if a footer is added to the website. I want to contribute to the project so please assign me this task.

**Comment by Tarun2605** [comment]
I am interested in this task please assign this to me. Thanking you in advance.

**Comment by SumitKumar-17** [comment]
@VanshKing30 
I want to work on this issue. Can you assign this issue to me under GSSoc'24?

**Comment by VanshKing30** [comment]
Can you guys please provide me with a footer image ??

**Comment by Tarun2605** [comment]
@VanshKing30 yes, this is one of my templates kindly suggest me any changes that you feel are necessary. Kindly find the screenshot attached.
![Screenshot 2024-05-11 004149](https://github.com/VanshKing30/FoodiesWeb/assets/124193280/ddb8fe0d-bc4a-486c-8b6f-66c78204bd06)

**Comment by mutcherlarahulkumar** [comment]
Subject: Request to Contribute to the development of footer in the website

Dear Project Admin,

I hope this message finds you well. My name is Mutcherla Rahul Kumar and I'm writing to express my interest in contributing to Foodies. I've been following the project for some time and I'm impressed by the work being done.

I would greatly appreciate it if you could consider assigning me the task of designing the footer. I'm eager to collaborate with the team and contribute to the project's success. And i would like to add up the footer image as reference.

![Screenshot 2024-05-11 172844](https://github.com/VanshKing30/FoodiesWeb/assets/120319439/9f38dad3-062f-4735-8669-866fae93b236)

Thank you for your time and consideration. I look forward to hearing from you soon.

Best regards,
Mutcherla Rahul Kumar.

**Comment by Shruti-Sawant** [comment]
I am proficient in creating responsive footers that adapt well to various screen sizes and devices. Assign this project to me under Gssoc'2024

**Comment by reshamsai150** [comment]
The website footer is missing i want to create a  responsive footer  for the website assign this issue to me @VanshKing30

**Comment by Karankumar2004** [comment]
> Subject: Request to Contribute to the development of footer in the website
> 
> Dear @VanshKing30,
> 
> I hope this message finds you well. My name is Mutcherla Rahul Kumar and I'm writing to express my interest in contributing to Foodies. I've been following the project for some time and I'm impressed by the work being done.
> 
> I would greatly appreciate it if you could consider **assigning me the task of designing the footer**. I'm eager to collaborate with the team and contribute to the project's success. And i would like to add up the **footer image as reference**.
> 
> I am proficient in creating responsive footers that adapt well to various screen sizes and devices. Assign this project to me under Gssoc'2024
> 
> ![Screenshot 2024-05-11 172844](https://private-user-images.githubusercontent.com/120319439/329779663-9f38dad3-062f-4735-8669-866fae93b236.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2ODgzNDIsIm5iZiI6MTcxNTY4ODA0MiwicGF0aCI6Ii8xMjAzMTk0MzkvMzI5Nzc5NjYzLTlmMzhkYWQzLTA2MmYtNDczNS04NjY5LTg2NmZhZTkzYjIzNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNFQxMjAwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzNjYzBlNjA4M2EyYjlkMGRlMTc0ZDQyZGU4YjU5NjBiYTcyNjFiNTA2NzlmYTUzMmQ2ZTBmZWUwMTAzY2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wd2IuoMh1oRhSWtxYkKmEDi2j-wFcvzeuyKFAYOYP84)
> 
> Thank you for your time and consideration. I look forward to hearing from you soon.
> 
> Best regards, Mutcherla Rahul Kumar.

Do add social media links.

**Comment by mutcherlarahulkumar** [comment]
please look into #152 issue and merge the pr i have updated the changes
suggested by u
