### ISSUE TITLE
BUG: Alignment Issue with Login/Sign-Up Page Messages on Mobile Screen

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The messages "Already have an account? Sign in" and "Don't have an account yet? Sign up" on the login/sign-up page are not aligned properly on mobile screens. This misalignment affects the visual appeal and user experience on mobile devices.

![login-signup](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/f39621b9-ac59-436e-b4a4-b28b775418b7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, fix that
