### ISSUE TITLE
BUG: Mistake in the signup page

### ISSUE THREAD

**Issue by namandude** [VanshKing30/FoodiesWeb#263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey there is the little issue there i saw while signing in there is semi colon and bracket which not correctly closed so appearing in the screen which is the mistake i want to fixt that.
![image](https://github.com/VanshKing30/FoodiesWeb/assets/118013565/2d6fcea7-8188-444a-8f1d-8f9c50af774d)
Please assign this to me .
Thank You!

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok fix that
