### ISSUE TITLE
BUG: Wrong message while logging in

### ISSUE THREAD

**Issue by anuragnegi000** [VanshKing30/FoodiesWeb#274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

While logging in it should show successful login instead of Unable to login

https://github.com/VanshKing30/FoodiesWeb/assets/115611556/6fdaae08-d4fa-45ed-9836-055cad9aa02d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
> @hustlerZzZ add labels and assign this issue to me

Okayy, Go ahead
