### ISSUE TITLE
BUG: no change of color of footer in light and dark modes

### ISSUE THREAD

**Issue by the-code-artist** [VanshKing30/FoodiesWeb#281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

the theme color of the footer is same in both light and dark modes
Light mode
![image](https://github.com/VanshKing30/FoodiesWeb/assets/115625321/fcc00289-b433-4096-8125-055a7c0f76f0)
Dark mode
![image](https://github.com/VanshKing30/FoodiesWeb/assets/115625321/49d4e83c-bf0f-4034-85d6-b40a0be45fcf)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by the-code-artist** [comment]
hey @hustlerZzZ 
I am excited to fix this issue.
Please assign me this issue under GSSOC'24

**Comment by hustlerZzZ** [comment]
> hey @hustlerZzZ I am excited to fix this issue. Please assign me this issue under GSSOC'24 !!

ok sure, start working on it.
