### ISSUE TITLE
Feat: Add contact details in the footer

### ISSUE THREAD

**Issue by the-code-artist** [VanshKing30/FoodiesWeb#282]
### Describe the feature

I would like to add the contact details of the creators in the footer
This would make the project more reliable!!

### Add ScreenShots

I would like to add the contact details beside "Company" in the footer
![image](https://github.com/VanshKing30/FoodiesWeb/assets/115625321/bad50cc1-2209-4c42-a257-46950dfdffc0)
this section contains social profile links of the creators

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by the-code-artist** [comment]
hey @hustlerZzZ 
I am excited to add this new feature to the project.
Please assign me this issue under GSSOC'24 !!

**Comment by hustlerZzZ** [comment]
What are you going to add... As there are no contact details...

**Comment by the-code-artist** [comment]
contact details includes the social media profiles of the developers like linkedin and others.
we can also create social media page for canteen and that link can also be attached in this contact details section if needed.
it would make the project more reliable.

**Comment by hustlerZzZ** [comment]
> contact details includes the social media profiles of the developers like linkedin and others. we can also create social media page for canteen and that link can also be attached in this contact details section if needed. it would make the project more reliable.

Ok Start Working on this...
