### ISSUE TITLE
BUG: Dark Mode for Rate-us section

### ISSUE THREAD

**Issue by Varshi45** [VanshKing30/FoodiesWeb#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have noticed an issue where the background of the "Rate-Our-Website" section is **not changing** when switching to dark mode. I would love to contribute to the project by fixing this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok start working on this!
