### ISSUE TITLE
creating fixed navbar along with framer-motion scroll feature

### ISSUE THREAD

**Issue by powerstone666** [VanshKing30/FoodiesWeb#29]
fixing navbar for bettwe accesiblity in navigating through pages and using framer motion scroll feature to make UI attractive by having progressive scroll bar for a better view

**Comment by VanshKing30** [comment]
@powerstone666 Can we connect on discord send me your discord id

**Comment by powerstone666** [comment]
imranpasha666

**Comment by VanshKing30** [comment]
@powerstone666 I have assigned you the issue under gssoc , raise the pr when it is done

**Comment by SumitKumar-17** [comment]
@VanshKing30 I want to work on this issue. Can you assign this issue to me under GSSoc'24?

**Comment by powerstone666** [comment]
im already doing it
