### ISSUE TITLE
BUG: Alignment Issues on About Page on Mobile Screen

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There are alignment issues on the About page when viewed on mobile screens. Elements are not properly aligned, impacting the readability and aesthetics of the page. This needs to be fixed to ensure a consistent and user-friendly experience across all devices.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Go ahead
