### ISSUE TITLE
DOC: Add License

### ISSUE THREAD

**Issue by Priyanshu2631** [VanshKing30/FoodiesWeb#291]
### What's wrong with the existing documentation

I want to add MIT License to this repository, kindly assign me this issue under GSSOC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
> ### What's wrong with the existing documentation
> I want to add MIT License to this repository, kindly assign me this issue under GSSOC'24
> 
> ### Add ScreenShots
> _No response_
> 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Okk
