### ISSUE TITLE
Feat:Search bar

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#293]
### Describe the feature

Want to Add Search bar so that user can search that Canteen

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/9fa511c2-fa20-44aa-b80b-12862d011e6c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
okk

**Comment by hustlerZzZ** [comment]
Will you also add search functionality or just the search bar?

**Comment by nishant0708** [comment]
@hustlerZzZ both
