### ISSUE TITLE
Feat:  Add "Remember Me" Section for Authentication 

### ISSUE THREAD

**Issue by codercake** [VanshKing30/FoodiesWeb#302]
### Describe the feature

The “Remember Me” feature for authentication is designed to improve user experience by reducing the frequency of login prompts. When a user selects “Remember Me” during login, the system stores a persistent cookie in the user’s browser. This cookie allows the system to recognize the user’s device and browser for a set period, typically ranging from several days to a few months.

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/117517206/2f6f9d01-5317-4f90-9589-85a63cc1589d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Start working on this!
