### ISSUE TITLE
BUG: Restrict Access to Home and About Pages to Logged-In Users Only

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, users can access the Home and About pages without logging in or signing up. To enhance security and user experience, these pages should only be accessible to logged-in users.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
I want to apply middleware to ensure that users without authentication can't access these pages. Please assign this issue to me!

**Comment by hustlerZzZ** [comment]
> I want to apply middleware to ensure that users without authentication can't access these pages. Please assign this issue to me!

OK, Great idea
