### ISSUE TITLE
BUG: Logout Button Renders to Signup Page Without Removing User Token

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, when clicking on the logout button, the application directly renders the signup page without properly removing the user token. This issue needs to be addressed to ensure that the user is fully logged out and the token is cleared before redirecting to the signup page.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok start working on this
