### ISSUE TITLE
BUG: Enhancement of the Header

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current header of the application needs enhancements to improve its design, functionality, and user experience. This includes updating the layout, adding new features, and ensuring it is responsive across all devices.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok
