### ISSUE TITLE
BUG: No separate button for canteen owners to access their canteen details

### ISSUE THREAD

**Issue by Praveenkumar5048** [VanshKing30/FoodiesWeb#316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello Project Admin, the bug i encountered is, that after the login as canteen user the route is directly redirected to section/canteenId, there is no separate button in the Home Page Navbar to access this page.
The problem here is the canteen owner finds it inconvenient to navigate between other routes and his canteen section.

What I would like to include is, after successful login all the users are redirected to home page only and here if the user is canteen owner a separate button "My Canteen" will be shown. By clicking this he can access the route section/canteenId to find  all their canteen details.

Please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Great, Idea start working on this
