### ISSUE TITLE
BUG: Visibility button has been used incorrectly

### ISSUE THREAD

**Issue by AkhilaSunesh** [VanshKing30/FoodiesWeb#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Location : login and sign up page 

When we click on the eye, the text should be visible
![image](https://github.com/VanshKing30/FoodiesWeb/assets/140897461/92b29f50-313f-41fb-b21d-7f24fccf1e98)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sohail0khan** [comment]
hey  please assign this problem to me
I am a new  contributor  i think i can do this

**Comment by hustlerZzZ** [comment]
Ok start working on this, @sohail0khan if @AkhilaSunesh didn't complete the assignment in 2-3 days then I will assign this to you.
