### ISSUE TITLE
BUG: Spell issue

### ISSUE THREAD

**Issue by AkhilaSunesh** [VanshKing30/FoodiesWeb#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In the github page
![image](https://github.com/VanshKing30/FoodiesWeb/assets/140897461/1a1a9e5a-9697-4136-b4e9-742278157b8d)
Spell errors are considered as long as one maintains their professionalism. Kindly allow me to resolve this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok
