### ISSUE TITLE
Enhancement :  Enhancement the Login/Register page with borders. 

### ISSUE THREAD

**Issue by agrwal697** [VanshKing30/FoodiesWeb#328]
### Describe the feature

I think if the Login/Register page had a border-bottom in every text item, it would have better UI and also it is not aligned properly. I would also like to make it responsive.
Please Assign me this issue with the label and level of GSSOC.

### Add ScreenShots

screenshots:

Before:

![image](https://github.com/VanshKing30/FoodiesWeb/assets/128716726/b8b92e3b-1277-46b3-8e63-73e60c7c5270)

After:

![image](https://github.com/VanshKing30/FoodiesWeb/assets/128716726/7ec89dcf-afb2-4221-829b-cd95cf0ad370)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, start working on this

**Comment by agrwal697** [comment]
sir, If it is possible than change the label gssoc to gssoc'24 because this PR not shown in my learderboard.
