### ISSUE TITLE
Feat:Want to Fix Nav Bar 

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#331]
### Describe the feature

Nav Bar is Not Good there is repeated icons

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/de6d413a-865b-4ab8-b6ff-bd101f512684)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok fix that

**Comment by JaiBansal007** [comment]
I Want To Work on this issue . Could you please Assign me this task? @VanshKing30
