### ISSUE TITLE
BUGS related to handling UseAuth() custom hook and clearing localStorage data after logout.

### ISSUE THREAD

**Issue by Praveenkumar5048** [VanshKing30/FoodiesWeb#334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

1.The code has auth useContext setup to store the authentication state of user. But this variable "isAuthenticated" is not updated
properly. when the user logIn this variable should be set to true, but this is not done in the code. And also it should be set to false when user log out. These changes must be done to efficiently manage the user authentication states.

2. The JWT token stored in the local storage after canteen user signUp, is not cleared when the user logout. This creates problem when another user, who is not canteen owner  log In in same system/device.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
@Praveenkumar5048 Hey, start working on this
