### ISSUE TITLE
BUG:When Someone click on About US He is Getting Looged Out

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

https://github.com/VanshKing30/FoodiesWeb/assets/101548649/ddaa3fd7-5fab-4ee5-8112-83e7f26abce2

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok fix that
