### ISSUE TITLE
Feat:Dark Mode Not Working in Canteen End 

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#338]
### Describe the feature

In Canteen End Dark Mode is not working i want to Fix That

### Add ScreenShots

https://github.com/VanshKing30/FoodiesWeb/assets/101548649/1adbc822-55a1-4007-8d48-8bce773d7ad0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Fix it
