### ISSUE TITLE
Improvment Home Page

### ISSUE THREAD

**Issue by ankitgupta143** [VanshKing30/FoodiesWeb#34]
### Describe the feature

I can Improve the Home page like by adding location or map features so that user can search nearby restaurant, improve the button with good animation, adding well structure footer and add query section.
@VanshKing30  Kindly assign it to me under GSSOC'24.

### Add ScreenShots

Also There is no login button to render login page if the user is on sign up page
![Screenshot 2024-05-10 223243](https://github.com/VanshKing30/FoodiesWeb/assets/114281117/67b8a40b-6409-4c09-a220-aa5477cafd8f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Hey @ankitgupta143 I really like your issue 
But For now only start working on the "Also There is no login button to render login page if the user is on sign up page"
this issue , later on we will look into the nearest restaurent feature

**Comment by AmrutaZagade** [comment]
Hey @VanshKing30 I would like to work on this task. Can you please assign it to me

**Comment by ankitgupta143** [comment]
@VanshKing30 please check sir I've updated it and accept pull request!

**Comment by ankitgupta143** [comment]
@VanshKing30 Issue number is 34

**Comment by ankitgupta143** [comment]
@VanshKing30 Issue number of PR is 72
