### ISSUE TITLE
BUG:SignUp page Visibility

### ISSUE THREAD

**Issue by amantaphelix** [VanshKing30/FoodiesWeb#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I would like to request to be assigned to the issue regarding the signup page visibility in our project. The current implementation of the signup page is not fully visible, and its contents are extending beyond the screen’s viewable area. This issue makes it difficult for users to access all the form fields and buttons, negatively impacting the user experience.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, start working on this
