### ISSUE TITLE
BUG: Multiple footers in the same page

### ISSUE THREAD

**Issue by the-code-artist** [VanshKing30/FoodiesWeb#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

2 footers are shown on the same page( add products page)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/115625321/063885b8-cfc4-458c-8374-6e68a5d5583f)
There need to be only one footer.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by the-code-artist** [comment]
hey @hustlerZzZ 
I am interested in resolving this bug and contribute to the project.
please do assign me this issue under GSSOC'24 !!

**Comment by hustlerZzZ** [comment]
ok fix that

**Comment by the-code-artist** [comment]
hey @hustlerZzZ 
thanks for adding the labels!!
can you also assign me this issue as well as it is necessary in the competition
Thank you

**Comment by omrakibe** [comment]
hey @hustlerZzZ
I am interested in resolving this bug and contribute to the project.
please do assign me this issue under GSSOC'24 !!

**Comment by hustlerZzZ** [comment]
> hey @hustlerZzZ I am interested in resolving this bug and contribute to the project. please do assign me this issue under GSSOC'24 !!

Ok Assigning this to you

**Comment by omrakibe** [comment]
will anyone help me
