### ISSUE TITLE
BUG: Fixed Icon of Password and confirmed password field

### ISSUE THREAD

**Issue by Kiran-pande-30** [VanshKing30/FoodiesWeb#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The eye icons for the password and forgot password fields in the sign-up form are not correctly configured.
![image](https://github.com/VanshKing30/FoodiesWeb/assets/105718863/e9b26abe-a8a5-4c5b-a0a2-846e779d5376)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok fix it
