### ISSUE TITLE
Feat: UI improvement in the contact page

### ISSUE THREAD

**Issue by arpy8** [VanshKing30/FoodiesWeb#349]
### Describe the feature

I would like to improve the ui of the contact us page.

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/74809468/631c57b1-936e-44be-acda-ee2d11f9472c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok , go ahead!
