### ISSUE TITLE
BUG: Successful Login Does Not Redirect to Home Page

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When attempting to log in, the user receives a message indicating a successful login, but the application does not redirect to the home page as expected.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Saksham2k3s** [comment]
Please assign me to this issue at level 2. I believe there is an issue with token creation.

**Comment by hustlerZzZ** [comment]
Start working on this @Saksham2k3s
