### ISSUE TITLE
BUG: Improve Canteen Section Page for Light and Dark Mode

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The current canteen section page needs improvement to enhance user experience and functionality, especially considering light and dark mode preferences.
![add](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/af8e13bf-b7df-44e0-8d6e-b9f3bf2f06a7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
ok, kindly proceed!

**Comment by Saksham2k3s** [comment]
Hey @hustlerZzZ ,
Could you please update "Improve Canteen Section Page for Light and Dark Mode #351" to level two? This task involves significant front-end work.
