### ISSUE TITLE
Feat:Canteen Navbar should be Different

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#357]
### Describe the feature

See currently when user clicks on home he reaches /home route .but for user who is logged in cateen when he click on home he should redirect to /section.
plus Canteen Navbar should have profile icon and other necesarry things which i could do
so there Shold be 2 Navbar and i will ensure proper functionality of both

### Add ScreenShots

no ss required

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
ok start working on this
