### ISSUE TITLE
Feat:Want to Update Canteen Backend so that User Can Add Fooditem Image & Description

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#362]
### Describe the feature

Want to Update Canteen Backend so that User Can Add Fooditem Image & Description.
Currently user can Add limited fields  by Adding images They Can Customize their Menu's.

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/dcdb39f8-81fe-4f69-b62d-d5074016b92f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok start working on this
