### ISSUE TITLE
Feat: Update favicon

### ISSUE THREAD

**Issue by heli0707** [VanshKing30/FoodiesWeb#363]
### Describe the feature

![image](https://github.com/VanshKing30/FoodiesWeb/assets/95361125/4679b867-7b33-4bf0-911a-ab676f867d49)

To enhance the visibility of the logo in the favicon, we need to remove the white background. This will ensure the logo is clearly visible and stands out against different browser themes.

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/95361125/8ac949b3-ce09-4408-9a82-378c02c3c780)

I will remove the white background to ensure it appears clearly against any browser theme. This will result in a clean, professional look similar to the "ResourceHub" example provided.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Santosh130602** [comment]
can i work ffor this issues

**Comment by Santosh130602** [comment]
can i work on this issue

**Comment by hustlerZzZ** [comment]
ok work on this
