### ISSUE TITLE
BUG:Contact us page is not responsive.

### ISSUE THREAD

**Issue by meetarora10** [VanshKing30/FoodiesWeb#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The contact us page is not responsive.
Assign this task to me and I can make this page completely responsive suitable for various devices.
![Screenshot (497)](https://github.com/VanshKing30/FoodiesWeb/assets/143121854/fd50c610-9716-4eaf-9556-8eb021fea7b2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, assigning this to you

**Comment by meetarora10** [comment]
Hi @hustlerZzZ  thank you for assigning me but this issue is already completed now.
