### ISSUE TITLE
Feat: Strong Password will only be accepted

### ISSUE THREAD

**Issue by yujit2003** [VanshKing30/FoodiesWeb#37]
### Describe the feature

Currently during signup page, one can authenticate if he have entered easy password

I want to implement where certail checks are done
1. password length > 8
2. one Uppercase and one Lowercase Alphabet
3. using special character

### Add ScreenShots

I would love to work in this issue as the risk of hacking the user account would be reduced.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Will you use any kind of library for this ??

**Comment by farzaneh-haghani** [comment]
I want to work on it please. I can do it by using regex.

**Comment by yujit2003** [comment]
I am thinking of using js regex library, if you have any other suggestions I could work on that library or even write my own function

Please assign this to me so that I could start working on this under GSSOC

**Comment by RakshitaJain2126** [comment]
Could you assign this feature implementation to me? I can create a function for this so that users can authenticate only if he/she has entered strong password.

**Comment by yujit2003** [comment]
@VanshKing30 I have raised A PR kindly review it to resolve this issue

**Comment by VanshKing30** [comment]
Thanks Mate
