### ISSUE TITLE
Feat:Logout Button Not Working It is just Redirecting

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#371]
### Describe the feature

Logout button is not removing necesaary info from local storage 

### Add ScreenShots

i will fix that

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Can you explain what unnecessary info is removed, i think removing jwt token is good if the user is logging out? @nishant0708

**Comment by hustlerZzZ** [comment]
Start working on this!
