### ISSUE TITLE
BUG:Registration and login both are not working

### ISSUE THREAD

**Issue by anwesha2002** [VanshKing30/FoodiesWeb#373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

after filling details when trying to submit the register form it is showing already exists and upon login it is not working. 
there is also a similar kind off issue #346 
is it done or can i work on this issue?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
You can work on #346 @anwesha2002

**Comment by anwesha2002** [comment]
@hustlerZzZ can i work on this issue #346 . I checked right now and the issue still exists and sign up is also not working
![Screenshot 2024-06-27 193728](https://github.com/VanshKing30/FoodiesWeb/assets/116761608/f88be172-e8b9-496f-8bda-c2624c815dee)
showing something like this
