### ISSUE TITLE
Feat:Allow Canteen Admins to Update food item Images and Description

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#379]
### Describe the feature

Currently Canteen can only edit dish name only i want to update that functionality so that canteen can update images as well as description of food

### Add ScreenShots

no ss required

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok start working on this
