### ISSUE TITLE
Feat:  ADDING BEM NAMING CONVENTION

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [VanshKing30/FoodiesWeb#384]
### Describe the feature

I want to add the BEM naming convention to all the files so that it will be easy to understand for all .

### What is BEM Naming Convention

It is a known fact that the right styleguide can significantly increase development speed, debugging, and the implementation of new features in legacy code. Sadly, most CSS codebases are sometimes developed without any structure or naming conventions. This leads to an unmaintainable CSS codebase in the long term.

### Add ScreenShots

![Screenshot 2024-06-28 094223](https://github.com/VanshKing30/FoodiesWeb/assets/118350936/dac3ce1c-9db1-477b-905b-018d70b49c3e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
BEM notation is a good approach, start working on this @Ayushmaanagarwal1211
