### ISSUE TITLE
CI/CD implementation

### ISSUE THREAD

**Issue by muskandn** [VanshKing30/FoodiesWeb#39]
### Describe the feature

Key advantages of using GitHub Actions for CI/CD pipelines: GitHub Actions is made by and for developers, so you don’t need dedicated resources to set up and maintain your pipeline. There’s no need to manually configure and set up CI/CD. You don’t have to set up webhooks, you don’t have to buy hardware, reserve some instances out there, keep them up to date, do security patches, or spool down idle machines. You just drop one file in your repo, and it works. 

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/99585352/8ed82f9a-d099-4d2a-8ed8-edb39363b1b7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
@iritikyadav123 Explain me the approach in discord 
here's my discord id : Vansh5238
