### ISSUE TITLE
BUG: Extra Space Between Heading "Trending Food and Health News" and New Cards on News Page

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an extra space appearing between the heading "Trending Food and Health News" and the new cards on the news page. This issue affects the visual layout and should be addressed to ensure a more cohesive design.

![extra spacing](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/39bfe405-b942-417d-874a-d5196f769ea7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, Assigning this issue to you.
