### ISSUE TITLE
Feat: Limit Character Count in News Card Description with "Read More" Button

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#391]
### Describe the feature

The news card descriptions currently display full text, which can vary in length and affect the uniformity and visual appeal of the news cards. To improve the design and readability, each news card description should display a fixed number of characters followed by "..." and a "Read More" button.

### Add ScreenShots

![read more](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/86fee06d-5c6f-430f-90a0-4f7500feeafa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, Assigning this issue to you.
