### ISSUE TITLE
Feat: Add Social Media Links to Canteen Profile Section or Contact Information

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#392]
### Describe the feature

To enhance user engagement and provide more information about the canteen, social media links should be added to the canteen's profile section or contact information. This will allow users to follow and learn more about the canteen through their social media channels.

### Add ScreenShots

![contact-from](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/1705ef4d-2b0f-405f-b392-af7a35033d05)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, Assigning this issue to you.
