### ISSUE TITLE
Feat: Enhancement of Canteen Profile Page

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#393]
### Describe the feature

The current canteen profile page lacks detailed information and visual appeal. Enhancing the profile page will provide a more informative and engaging experience for users. This includes adding social media links, updating design elements, and including additional information about the canteen.

### Add ScreenShots

![contact-from](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/62328e26-b4ed-4f42-92f9-e51afb401464)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, Assigning this issue to you.
