### ISSUE TITLE
Feat:Want to fix UI of Add Product Page 

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#396]
### Describe the feature

Currently the Addproduct page is overflowing and it is hiding buttons that are on the top

### Add ScreenShots

![Screenshot 2024-07-01 002854](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/9b968229-424b-469e-9af7-cced20e7759e)
![Screenshot 2024-07-01 002859](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/4791485f-75aa-4e85-a49b-3646ee6ab5fe)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, Assigning this issue to you.
