### ISSUE TITLE
Feat:Want to Update Canteen Cards

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#398]
### Describe the feature

Hey want to update Canteen cards currently has no fixed width or length which is making site inconsistent
plus canteen card should also have ratings as well so i will add those and some other fields like opening and closing time

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/e1155b9b-90b6-41da-8050-9b3a744261da)
I will fix this whole card full ensure responsiveness and dark mode as well

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, Assigning this issue to you.
