### ISSUE TITLE
BUG: Want to fix Design issues with dark mode and add dish page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [VanshKing30/FoodiesWeb#399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The dark mode is not implemented correctly for all pages like somewhere the text in the input fields also changing to white which makes it invisible 
The dark mode is not implemented for review us page 
THe see products page doesn't contains dark mode 
The add dish form overlapping with the heading 
The close button is not working for the modal opening for editing of dish 
I want to fix that and also want to enhance that

https://github.com/VanshKing30/FoodiesWeb/assets/118350936/66928a3b-a4ee-47b8-8984-3e18318b5447

https://github.com/VanshKing30/FoodiesWeb/assets/118350936/3029a9cb-329f-4613-ac34-5229eb7c36aa

https://github.com/VanshKing30/FoodiesWeb/assets/118350936/4329bd8f-c669-4ddb-b61d-30478df9691c

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, Assigning this issue to you.

**Comment by priyankMS** [comment]
, I want to work on this feature under GSSOC 24 please add a label to it and assign it to me.
