### ISSUE TITLE
It does not have a good contribution guide for beginner contributer's

### ISSUE THREAD

**Issue by VanshKing30** [VanshKing30/FoodiesWeb#4]
Please work on this issue , try adding a a contribution guide on it which will make the new contibuters easy to contibute.

**Comment by Vanshika-73** [comment]
@VanshKing30 you mean .md file? Please assign me this issue under GSSOC 24.

**Comment by VanshKing30** [comment]
Yeah The .md file , I am assigning you this Issue.

**Comment by VanshKing30** [comment]
@Vanshika-73 Have you completed the task ??

**Comment by Vanshika-73** [comment]
I will. GSSOC contributions will start from today 7pm sharp. So will raise
a pr after that.
