### ISSUE TITLE
Feat: The animation effect when hovered on the navbar icons is very simple 

### ISSUE THREAD

**Issue by VanshKing30** [VanshKing30/FoodiesWeb#40]
### Describe the feature

Could someone please enhance the hover effect on the icons in the navbar? Looking to make it more polished and engaging. Thanks in advance!

### Add ScreenShots

Nil

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by harshnayangithub** [comment]
I want to contribute to this issue please assign it to me

**Comment by VanshKing30** [comment]
Try Doing this asap !! I have assigned this task to you , raise the PR when it is done .

**Comment by harshnayangithub** [comment]
while setting up the project locally, backend server is not running, it showing error in build logs. 
Check it out and help me tackle this:-
![Screenshot 2024-05-11 at 12 43 34 PM](https://github.com/VanshKing30/FoodiesWeb/assets/126700987/7535ded5-8457-40f8-8f5a-cc7e5de13d54)

**Comment by RakshitaJain2126** [comment]
I’d like to collaborate on this task. Could you assign me as well?

**Comment by Manaswini123456** [comment]
I would also like to collaborate kindly assign me with this issue, so that I can provide my insights

**Comment by VanshKing30** [comment]
@RakshitaJain2126 and @harshnayangithub Both of you can start working on it !! If you need any helps 
just discord dm me  , my id : Vansh5238

**Comment by Manaswini123456** [comment]
@VanshKing30 Kindly assign me with the issue, as I can provide my insights and solutions too. I am also a GSSOC'24 contributor.

**Comment by VanshKing30** [comment]
@Manaswini123456 I have alredy assigned 2 persons into this task , and its not that heavy task 
I am sorry but look for another issues ;(

**Comment by Manaswini123456** [comment]
Sure, will do that

**Comment by RakshitaJain2126** [comment]
Sure @VanshKing30 .I am going to start working on it and create PR soon.
