### ISSUE TITLE
Feat: Make website SEO friendly

### ISSUE THREAD

**Issue by chaanakyaaM** [VanshKing30/FoodiesWeb#413]
### Describe the feature

I would like to add appropriate meta tags for making the website SEO friendly. 

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok, do that! 
BTW we are in react and react is bad for SEO
