### ISSUE TITLE
BUG: Add food item card is overlapping the footer

### ISSUE THREAD

**Issue by the-code-artist** [VanshKing30/FoodiesWeb#414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Add food item card is overlapping the footer and is effecting the look of the application
![image](https://github.com/VanshKing30/FoodiesWeb/assets/115625321/9b16fbd4-6887-4568-8004-94e22f65aacc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by the-code-artist** [comment]
hey @hustlerZzZ 
I would like to resolve this bug and contribute to the project!!
please assign me this issue under GSSOC'24.

**Comment by hustlerZzZ** [comment]
> hey @hustlerZzZ I would like to resolve this bug and contribute to the project!! please assign me this issue under GSSOC'24.

Start working on this
