### ISSUE TITLE
Feat: Add contact us page in the footer

### ISSUE THREAD

**Issue by the-code-artist** [VanshKing30/FoodiesWeb#415]
### Describe the feature

add a redirect component "Contact Us" in the footer which will navigate to contact page

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/115625321/ffbb5c50-2840-4d8d-94d2-17b5ba41221f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by the-code-artist** [comment]
hey @hustlerZzZ 
I would like to develop this feature and contribute to the project!!
please assign me this issue under GSSOC'24.

**Comment by hustlerZzZ** [comment]
OK @the-code-artist
