### ISSUE TITLE
Feat: Elevate the emoji which is selected in the rate us page

### ISSUE THREAD

**Issue by the-code-artist** [VanshKing30/FoodiesWeb#416]
### Describe the feature

Elevate the emoji which is selected in the rate us page such that user understands the rating they chose

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/115625321/0ebf65af-257a-435b-a422-af2139427d86)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by the-code-artist** [comment]
hey @hustlerZzZ 
I would like to develop this feature and contribute to the project!!
please assign me this issue under GSSOC'24.

**Comment by hustlerZzZ** [comment]
I think emoji's are already added
