### ISSUE TITLE
Feat:Want to Add proper Toast messages in Login and Signup Page

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#420]
### Describe the feature

![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/dd1b4545-fdcf-425a-a213-75b7b46d2cb8)
Currently no toast message is coming in login page and Signup page i will fix that

### Add ScreenShots

Na

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok do this
