### ISSUE TITLE
Feat:Want to Write Backend Of FeedBack Page Of Canteens

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#421]
### Describe the feature

Want to Write Below Component Backend 

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/182568c6-66c4-4666-868a-342ab139879f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok do it
