### ISSUE TITLE
Feat:Create News Cards

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#422]
### Describe the feature

Currently there is no news in newspage i will create a button through which user can post about food places and share their experience. i will write both backend with md file support

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/1c69b5ce-cd99-4601-87dd-536f08c291b9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
ok do this

**Comment by Manohar-04** [comment]
ok i can do
