### ISSUE TITLE
Feat: Add Contact Information to Canteen Page

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#430]
### Describe the feature

We need to add contact information to the canteen page to allow users to easily connect with the canteen staff for inquiries, orders, or feedback. This will enhance user experience and improve communication.

### Add ScreenShots

![canteen](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/25948583-48fd-4c28-932e-67b5835cb306)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by SuvvadaTejesh** [comment]
assign this issue to me

**Comment by hustlerZzZ** [comment]
Start working on this!
