### ISSUE TITLE
BUG: Fix Extra Space Between Feedback Input and Menu on Canteen Page

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is an unnecessary extra space between the feedback input field and the menu section on the canteen page. This issue affects the layout and visual consistency of the page. We need to adjust the spacing to ensure a more cohesive design.
![extra space](https://github.com/VanshKing30/FoodiesWeb/assets/129402285/5bedb6ce-58de-4025-9cfc-9bbf37bf4d1b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
fix it
