### ISSUE TITLE
BUG: Add Star Rating to Canteen Profile

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

We need to display a star rating on the canteen profile to provide users with a quick visual representation of the canteen's overall rating based on user feedback. This will help users make informed decisions and enhance the overall user experience.

![extra space](https://github.com/user-attachments/assets/221e5b20-336a-46eb-9d5d-44284bdbed8d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Kindly reupload the image

**Comment by Saksham2k3s** [comment]
Hi @hustlerZzZ,
Please check it now

**Comment by hustlerZzZ** [comment]
> Hi @hustlerZzZ, Please check it now

Ok do this
