### ISSUE TITLE
Feat:Error in updating Food items from Canteen End + This should be in Cards

### ISSUE THREAD

**Issue by nishant0708** [VanshKing30/FoodiesWeb#434]
### Describe the feature

there is error in updating Canteen FoodItem 

### Add ScreenShots

![Screenshot 2024-07-10 024617](https://github.com/VanshKing30/FoodiesWeb/assets/101548649/89c2c736-1345-461c-b15c-782e6270e57d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
ok fix it
