### ISSUE TITLE
Feat:Add Contributors Page to Display Project Contributors

### ISSUE THREAD

**Issue by pani2004** [VanshKing30/FoodiesWeb#438]
### Describe the feature

The contributors page will display the details of the contributors who have contributed to this project

### Add ScreenShots

![10 07 2024_23 05 55_REC](https://github.com/VanshKing30/FoodiesWeb/assets/154724111/43f0ead8-d62b-4862-a443-2e9a73a354de)
Will add the link in the marked area

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pani2004** [comment]
@hustlerZzZ Can I work on this?

**Comment by Bgmi10** [comment]
"I've implemented the Contributors page with infinite scroll, ensuring compatibility for both dark and light themes. The page is fully responsive across various devices. Ready to raise a PR. "

https://github.com/user-attachments/assets/9eab69c8-46cd-429e-90d0-585ca525d0a2

**Comment by hustlerZzZ** [comment]
Great work
