### ISSUE TITLE
BUG:Validating and alerting users when submitting an empty CONTACT US form.

### ISSUE THREAD

**Issue by amantaphelix** [VanshKing30/FoodiesWeb#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![WhatsApp Image 2024-07-15 at 18 23 25_244ebe27](https://github.com/user-attachments/assets/f373443c-9a3a-46be-82cc-6632bebfef24)
I would like to request the assignment of the issue related to validating and alerting users when submitting an empty form. I plan to implement a check in the handleEmailSubmit and handleSaveToDB functions to ensure users are notified if any required fields are left empty.

Thank you!

Best regards,
Amanta Phelix

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Ok
