### ISSUE TITLE
Feat: Adding the GSAP(JS LIBRARY) animations to the website

### ISSUE THREAD

**Issue by suraj-9849** [VanshKing30/FoodiesWeb#45]
### Describe the feature

So for this good website if animations are added then there will be an improvement in the UI of the website and also helps the user feel good

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/146669517/a7b90cf4-046e-4495-8e0b-81a3a6ab8a04)
all of them will be coming by sliding and the ui will be enhanced

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
This will simply make the website much slower , I dont want that Sorry
