### ISSUE TITLE
DOC: index.css

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [VanshKing30/FoodiesWeb#461]
### What's wrong with the existing documentation

I want to update the exisiting file 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AKSHITHA-CHILUKA** [comment]
please assign

**Comment by hustlerZzZ** [comment]
Okay start working on this

**Comment by AKSHITHA-CHILUKA** [comment]
Yeah thank you

**Comment by AKSHITHA-CHILUKA** [comment]
close the issue as the pull request is merged
