### ISSUE TITLE
DOC: Add env.example File for Environment Variable Configuration

### ISSUE THREAD

**Issue by vamshi726** [VanshKing30/FoodiesWeb#474]
### What's wrong with the existing documentation

To improve the onboarding process for new contributors and ensure consistent environment variable configuration across all development environments, we need to add an env.example file to the project. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Kindly dont create a pull request before I assign this to you @vamshi726

**Comment by vamshi726** [comment]
Ok
