### ISSUE TITLE
Feat: UI Improvement Drop down (User , canteen selection)

### ISSUE THREAD

**Issue by khushi747** [VanshKing30/FoodiesWeb#48]
### Describe the feature

I can improve the ui. I personally feel that using this dropdown for selection of user and canteen is a little bit old style. I can enhance this UI, and make button at the top, and by toggling it one can navigate it in user login screen or canteen login screen. Please allow me to work on it. Thankyou.

### Add ScreenShots

![image](https://github.com/VanshKing30/FoodiesWeb/assets/95963491/bdbdf3f1-51a5-43da-a4bf-47da33e30cef)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Cool Starting working on it , and then raise the PR when its done , dont forget to add ScreenShort for the changes you have made

**Comment by khushi747** [comment]
Sure, Thankyou.

**Comment by VanshKing30** [comment]
@khushi747 How long will it take to do this ??

**Comment by khushi747** [comment]
Yes, I am currently working on it and will have it submitted by the end of this week. Thank you for your patience.
