### ISSUE TITLE
Feat: Make Login & SignUp page more Impressive

### ISSUE THREAD

**Issue by sreevidya-16** [VanshKing30/FoodiesWeb#488]
### Describe the feature

I want to make Login and Sign up page more attractive, with authentication

### Add ScreenShots

![WhatsApp Image 2024-08-05 at 18 08 12_3bd33f97](https://github.com/user-attachments/assets/a991a222-5569-4c05-bff5-12554b011c0e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by sreevidya-16** [comment]
@VanshKing30, assign me this issue under GSSOC

**Comment by hustlerZzZ** [comment]
Heyy, that's some amazing UI @sreevidya-16 start working on this, assigning this to you
