### ISSUE TITLE
Feat: Improve Restaurant Differentiation for Better User Experience

### ISSUE THREAD

**Issue by SabanaSultana** [VanshKing30/FoodiesWeb#49]
### Describe the feature

As a user of the website, I've noticed a recurring problem: multiple restaurants sharing the same name (eg:ABC). This often leads to confusion when trying to find specific information or reviews for a particular restaurant. Restaurant names should be as unique as possible.

### Add ScreenShots

![Screenshot (1445)](https://github.com/VanshKing30/FoodiesWeb/assets/124595925/9c3dcbe8-17b7-49a8-b53c-6cd2e5ab3c3c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
How can you solve this issue ??

**Comment by SabanaSultana** [comment]
@VanshKing30  need change the name of the restaurants.

**Comment by VanshKing30** [comment]
That dosent seems like a good solution @SabanaSultana
