### ISSUE TITLE
Feat: Create backend for canteen rating

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#494]
### Describe the feature

Create a backend for the canteen ratings to display the overall rating of the canteen.

### Add ScreenShots

![ratings](https://github.com/user-attachments/assets/9b60728b-4550-45ff-9499-ef69c46c13be)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Go ahead implement this!
