### ISSUE TITLE
BUG: CORS Issue on Login

### ISSUE THREAD

**Issue by Saksham2k3s** [VanshKing30/FoodiesWeb#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is a Cross-Origin Resource Sharing (CORS) issue occurring on the login endpoint. Users are unable to successfully log in due to CORS errors, which are preventing the application from making requests to the server.

![cors](https://github.com/user-attachments/assets/e9a69a90-8e67-4091-8e43-1e91fc894e3a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
Fix it
