### ISSUE TITLE
DOC: add RatingStars.jsx 

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [VanshKing30/FoodiesWeb#497]
### What's wrong with the existing documentation

add RatingStars.jsx to components .
A component to display and handle ratings using star icons. Useful for reviews or rating food items and canteens.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by hustlerZzZ** [comment]
We are already having this!
