### ISSUE TITLE
Creating "Success" and "Error"  Utilities in  server to send response as object instead of json

### ISSUE THREAD

**Issue by Crazzy-novus** [VanshKing30/FoodiesWeb#5]
I can create a structured utilities which help to send response to api call.  Sending response as object is a good practice and it is a part of MVC pattern. I can create separate file for "**Success**" and "**Error**" response. Please assign this issue to me

**Comment by VanshKing30** [comment]
Start working on it , create a pull request when done

**Comment by rajksd01** [comment]
Hey @Crazzy-novus  are you working on it ?
If no, I would like to work on it.

**Comment by Crazzy-novus** [comment]
@rajksd01  I am working on it. It almost done
