### ISSUE TITLE
Feat: Add Confirmation Password for Enhanced Security

### ISSUE THREAD

**Issue by SabanaSultana** [VanshKing30/FoodiesWeb#50]
### Describe the feature

There's currently no confirmation password requirement on the website for SignUp. This oversight could lead to inadvertent or unauthorized changes, posing a risk to the security and integrity of user accounts. To fortify website security and prevent unintended alterations, it's imperative to introduce a confirmation password feature.

### Add ScreenShots

![Screenshot (1446)](https://github.com/VanshKing30/FoodiesWeb/assets/124595925/f0a7f297-c7b2-4e9e-892f-05a2574f888e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by yujit2003** [comment]
@VanshKing30 I have created a PR please review it and add it under GSSOC

**Comment by yujit2003** [comment]
@VanshKing30 Can you Please add level also in labels

**Comment by VanshKing30** [comment]
We have alredy use regex over there , i think there's no need to add this , if any one of you can work on google authentication 
i would love to assign you the taks

**Comment by yujit2003** [comment]
I would like to work on Google authentication please assign this to me

**Comment by SabanaSultana** [comment]
> We have alredy use regex over there , i think there's no need to add this , if any one of you can work on google authentication i would love to assign you the taks

@VanshKing30 I would like to work, pls assign me
