### ISSUE TITLE
BUG: Feedback can be easily given without login.

### ISSUE THREAD

**Issue by VigneshGadhari** [VanshKing30/FoodiesWeb#53]
### What happened?

I identified a potential security vulnerability in the feedback system. Currently, anyone can access the feedback form by simply typing "/home" after the base URL. This bypasses the login requirement and could allow anyone to submit false or misleading feedback. This would create problems for canteen owners who rely on genuine feedback to improve their services.

I'm participating in GSSOC'24 and I'm interested in addressing this security issue. I believe I can develop a solution that requires users to log in before submitting feedback, ensuring only authorized users can provide input @VanshKing30 .

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Cool !! Assigned you the task , Raise the PR when done
