### ISSUE TITLE
Feat: Implement forget password

### ISSUE THREAD

**Issue by Niharika0104** [VanshKing30/FoodiesWeb#54]
### Describe the feature

The application currently lacks the "Forgot Password" feature, which is crucial for user account recovery. This issue is to implement the necessary pages and functionality required for the "Forgot Password" feature.
#### Tasks:
1. **Create Forgot Password Page:** Develop a new page or modal for the "Forgot Password" functionality.
   - **Steps to Implement:**
     1. Design the user interface for entering email addresses for password reset requests.
     2. Implement the frontend components for the Forgot Password page/modal.
   - **Expected Behavior:** Users should be able to access the Forgot Password page/modal to initiate the password reset process.

2. **Backend Logic for Password Reset:** Develop backend logic to handle password reset requests and send reset instructions to the user's email.
   - **Steps to Implement:**
     1. Define API endpoints or backend routes to handle password reset requests.
     2. Implement logic to generate and store password reset tokens securely.
     3. Integrate with email services to send password reset instructions to users.
   - **Expected Behavior:** Upon submitting a password reset request, users should receive instructions on how to reset their passwords via email.

### Add ScreenShots

There is no forget password link on the sign in page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by riyasaxena32** [comment]
please assign this issue to me.I will add forget password in its login

**Comment by VanshKing30** [comment]
@Niharika0104 Will you be abel to do the both frontend and backend part ??

**Comment by Niharika0104** [comment]
@VanshKing30 yes

**Comment by codebreaker3008** [comment]
@VanshKing30  could you assign this to me ?

**Comment by Jish261203** [comment]
Hi @VanshKing30 ,

I'm enthusiastic about your project and would love to contribute to its improvement under GSSOC'24! Could you assign me the task ?

Looking forward to your response.

Best regards,
Jishnay

**Comment by sourav-sm** [comment]
Hey @Niharika0104 , I am  Sourav Mohanta , 3rd year Student of NIT Durgapur, I have previously contributed to p5js (Processing Foundation) , 
  I understand the issue and work on this challenging issue , Plz assign it to me

**Comment by Mandar007007** [comment]
Hey @Niharika0104 Please assign me this task because i have implemented this feature several times in my project.

**Comment by VanshKing30** [comment]
@sourav-sm and @Mandar007007 Text me the approach in discord 
here's my discord id: Vansh5238
