### ISSUE TITLE
Feat: Remove selection of account type on login page 

### ISSUE THREAD

**Issue by Niharika0104** [VanshKing30/FoodiesWeb#55]
### Describe the feature

We can remove the selection of account type from the login page. Instead, users will now only be prompted to enter their credentials for authentication.

Changes Made:
- Removed login  as election UI from the login page.

Reasoning:
By removing the account type selection from the login page, we streamline the login process and reduce complexity for users. They can now focus solely on logging in with their credentials without unnecessary choices.

### Add ScreenShots

Just remove the login as select element from the login page

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Assigned you this task !! Raise the PR when done

**Comment by Varsani2520** [comment]
i want to work with you ,please assign me ,i make a lots of real time website ,so i expert in that

**Comment by Niharika0104** [comment]
#93

**Comment by Niharika0104** [comment]
> #93
I created a pull request for this

**Comment by VanshKing30** [comment]
I have checked it !! Will merge it soon
