### ISSUE TITLE
BUG:Feedback Submitted even though no feedback given

### ISSUE THREAD

**Issue by panam1916** [VanshKing30/FoodiesWeb#56]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What happened?

I noticed that there is no feedback given but still when we click submit it succsesfully shown feedback submitted
![Isssue](https://github.com/VanshKing30/FoodiesWeb/assets/92396633/7f2e2930-11b0-406d-8382-0a8023bc7c59)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by panam1916** [comment]
can you please assign it to me?

**Comment by VanshKing30** [comment]
Where will you send the feedback ? What do you think should the feedback be sent to the canteen owners mail ??

**Comment by panam1916** [comment]
Firstly it succesfully show submit alert without given feedback and yes i think canteen owners can get mail can be good enhancement can you kindly allow me to do work on this?

**Comment by panam1916** [comment]
Please Can you assign it to me?

**Comment by VanshKing30** [comment]
For now only fix the first issue which you told me , regarding the feedback alert , create a new issue on the second part , we will discuss it over there .

**Comment by panam1916** [comment]
Ok as your wish and thanks for assign it to me

**Comment by VanshKing30** [comment]
Yeah Man !!

**Comment by panam1916** [comment]
I fix that issue of notification

**Comment by panam1916** [comment]
> For now only fix the first issue which you told me , regarding the feedback alert , create a new issue on the second part , we will discuss it over there .

Now can we talk about this?

**Comment by panam1916** [comment]
> Where will you send the feedback ? What do you think should the feedback be sent to the canteen owners mail ??

Now can we discuss about this?

**Comment by VanshKing30** [comment]
Sure Buddy !! Text me on my discord 
myd discord id : Vansh5238

**Comment by panam1916** [comment]
can i create issue for that?

**Comment by sanjay-kv** [comment]
Hi @VanshKing30 please label + request you to add me to the repo
