### ISSUE TITLE
BUG: Request to Address Password Hashing Issue in Database Population Script

### ISSUE THREAD

**Issue by Ninad-Patil** [VanshKing30/FoodiesWeb#57]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Description:
Upon running the populateDB script, user credentials are generated, but login attempts fail due to password hashing discrepancies. The issue stems from passwords not being hashed during database population, while the authentication process assumes hashed passwords. Consequently, the comparison in auth.js fails on this line of code: `await bcrypt.compare(password, user.password).` as both the passwords are in string format only.

Resolution:
To rectify this, I propose implementing a password hashing function within the populateDB script. This ensures that credentials are stored with hashed passwords, aligning with the authentication process and enabling successful logins.

Request:
 @VanshKing30 Kindly assign this issue to me under [gssoc'24].

Thank you,
Ninad

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aman0413** [comment]
Please assign to me because I have handle this issue in my previous project.

**Comment by VanshKing30** [comment]
I really liked your appraoch , and you have raise d apr for this !!

**Comment by Ninad-Patil** [comment]
@VanshKing30 can you please add labels to merged PR also
