### ISSUE TITLE
[Enhancement] Fixing the header

### ISSUE THREAD

**Issue by Disha-Hati** [VanshKing30/FoodiesWeb#6]
The Header padding and margin needs to be fixed. I'm GSSOC'24 contributor, Can you please assign this issue to me?

**Comment by nishant0708** [comment]
hey can you assign me this issue

**Comment by VanshKing30** [comment]
@Disha-Hati Please make changes and create a pull request.

**Comment by Disha-Hati** [comment]
> @Disha-Hati Please make changes and create a pull request.

Yes, sure

**Comment by powerstone666** [comment]
hey add Gssoc tags and level so that contributors can understand its part of Gssoc 24 and contribute to it

**Comment by powerstone666** [comment]
Even add the env and configuration of it in readme without it there would be lot of difficulty to set up project.....!

**Comment by VanshKing30** [comment]
> hey add Gssoc tags and level so that contributors can understand its part of Gssoc 24 and contribute to it

The GSSoC contribution hasn't started yet. As soon as it begins, I will assign the labels as well.

**Comment by VanshKing30** [comment]
> Even add the env and configuration of it in readme without it there would be lot of difficulty to set up project.....!

I would love if youw would do that , Please let me know if you want to i will assing this particulat task to you

**Comment by powerstone666** [comment]
sure

**Comment by VanshKing30** [comment]
> sure

Create a new issue and and ask me to assign this task to you !! 
The contribution period has started

**Comment by AbhiJay1287** [comment]
I'm GSSOC'24 contributor, Can you please assign this issue to me?
