### ISSUE TITLE
DOC: missing Code_of_conduct.md

### ISSUE THREAD

**Issue by space-monkey22** [VanshKing30/FoodiesWeb#60]
### What's wrong with the existing documentation

this repository is missing code_of_conduct.md file. 

Sample: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md

### Record

- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Please Create a COC file and make changes , as soon as the work is done , raise the PR.
