### ISSUE TITLE
Feat:UI Updation

### ISSUE THREAD

**Issue by StephenStolk** [VanshKing30/FoodiesWeb#62]
### Describe the feature

Improving the ui design of 'About Us' page.

### Add ScreenShots

Suggested changes:
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/bb6556b9-4875-4fa4-948f-6eb044ca3c9e)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/a1e0416c-2875-47b0-a1dd-ade5964edca3)

Color pallette:
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/76ae8e55-815f-48cb-841e-fe2993277850)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
That looks Pretty Good man !! I have assigned you this task , As soon as the work is done Raise the PR

**Comment by Chandan157** [comment]
Hello sir, I am Chandan. Under GSSOC'24, I would like to work on this issue. can you assign this issue to me!!

**Comment by VanshKing30** [comment]
Merged !!
