### ISSUE TITLE
BUG: User can move to home, about page without logging in by changing the url routes manually. There is no prevention of this in code.

### ISSUE THREAD

**Issue by StephenStolk** [VanshKing30/FoodiesWeb#63]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### What happened?

Problem creation:
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/866df10d-d73c-4985-8f80-c3a946d2ad5b)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/836e73de-6d0a-464d-8ad7-20f0ac8a0080)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/dc71aec0-07c2-4768-966f-6d6bb951c797)

There is no stoppage (as login needed) from entering the platform . 

I want to work on this

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VigneshGadhari** [comment]
I've already added this as an existing issue prior to this, you might want to uncheck that option
