### ISSUE TITLE
BUG:White shadow appearing on logout button background

### ISSUE THREAD

**Issue by SHUBHAMRAJPUT9665** [VanshKing30/FoodiesWeb#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

When we click on the logout button, a different white shadow appears in the background of the button
please assign this issue to me? I'd like to work on resolving it.
<img width="179" alt="btn" src="https://github.com/VanshKing30/FoodiesWeb/assets/113655062/4030dbf9-390c-4967-a91c-f1d41c9ad321">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
What changes will you make on the hover button

**Comment by SHUBHAMRAJPUT9665** [comment]
I will enhance the hover effect on the button to provide clearer visual feedback and improve user interaction

**Comment by SHUBHAMRAJPUT9665** [comment]
> What changes will you make on the hover button



> What changes will you make on the hover button


I will enhance the hover effect on the button to provide clearer visual feedback and improve user interaction

**Comment by VanshKing30** [comment]
Can you please satsify me with the screeshots
