### ISSUE TITLE
Adding icons to Home ,news, About us  on the navbar

### ISSUE THREAD

**Issue by Soumya6Tiwari** [VanshKing30/FoodiesWeb#7]
on the navbar we can assign icons to the different sections such as Home, News , about Us which would make it look better.

**Comment by Soumya6Tiwari** [comment]
@VanshKing30  Kindly assign me this issue under GSSOC'24 , this will be my first PR

**Comment by Soumya6Tiwari** [comment]
Yes ,please assign the gssoc label and level too

**Comment by VanshKing30** [comment]
I have assigned you this issue
