### ISSUE TITLE
Adding sessions to website

### ISSUE THREAD

**Issue by Yashasvi213** [VanshKing30/FoodiesWeb#73]
With the user authentication, it is crucial to also introduce sessions in our website
What I could provide is-
1) Designing Session Management Schema
2) Implementing Session Creation Endpoint
3) Secure Session Handling
4) Session Expiration Mechanism
5) Session Persistence

Please assign me this issue so that I can work on it.

**Comment by VanshKing30** [comment]
Text me the approach on discord 
id: Vansh5238

**Comment by Yashasvi213** [comment]
Okay sir

**Comment by nishant0708** [comment]
assign me this issue under gssoc24

**Comment by Tanu2205** [comment]
Can you please assign me this issue under Gssoc'24?

**Comment by VanshKing30** [comment]
@biswarup-naha Start working on it , raise the PR when done !!

**Comment by biswarup-naha** [comment]
@VanshKing30 I've raised the PR, you can review and merge.
