### ISSUE TITLE
Feat:Google authentication during login

### ISSUE THREAD

**Issue by yujit2003** [VanshKing30/FoodiesWeb#74]
### Describe the feature

Adding Google authentication on login page so that user can direct login without sign up

@VanshKing30 please assign this issue to me under GSSoc 

### Add ScreenShots

Google authentication 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Please explain a bit about how are you going to add google authentication ??

**Comment by SaurabhS55** [comment]
Hey @VanshKing30 I am Saurabh Salunke and I have prior experience of working with MERN stack. I would like to work on this issue. could you assign this issue to me with GSSOC'24 label.

Ok, now talking about Adding google authentication:-

1. We can do it using Passport.js npm library.
   we can follow this steps to do so :-
    - Create a button called "Login with Google"
    - At backend, create a route, say "/auth" and on that route create a middleware to use passport.js functionalities.
    - "/auth" route authenticate user gmail and return its credentials to frontend.
    - Finally, At frontend we will store that credentials in localstorage.
    
2. Using Google OAuth

**Comment by yujit2003** [comment]
@VanshKing30 i am thinking of doing this
Backend (Node.js)
1.Create a Google Cloud Platform (GCP) Project

2.Configure Passport.js:

3.Implement Routes:

4.Handle User Authentication:

Frontend -> 
1. Create Login Button:

2. Handle Authentication Response:

3. Store Authentication along with user role:

**Comment by VanshKing30** [comment]
Start working on it !! Assigner you the task !

**Comment by SaurabhS55** [comment]
Hey @VanshKing30 could you label this issue under GSSOC'24 label?

**Comment by yujit2003** [comment]
hey @SaurabhS55 let's connect and distribute work...

**Comment by yujit2003** [comment]
@VanshKing30 i have implemented frontend and created a PR.. will work on backend now...

**Comment by SaurabhS55** [comment]
@VanshKing30 I have implemented all required functionalities (frontend+backend part) and made PR. Please review this PR and label this issue under GSSOC'24.

**Comment by yujit2003** [comment]
Great @SaurabhS55 u don't work in team ig

**Comment by SaurabhS55** [comment]
Pardon me, but I have started working on this issue before assigning us. so, I have developed most of the features already .
