### ISSUE TITLE
Feat: The hover effect on the links in the navbar can be improved

### ISSUE THREAD

**Issue by Debarunn1806** [VanshKing30/FoodiesWeb#79]
### Describe the feature

Upon hovering on the links in the navbar the background changes to gray , rather than this we can add a hover effect along with a lightup on the navlinks. These changes can also be applied on the logout button.

### Add ScreenShots

![Screenshot 2024-05-12 050820](https://github.com/VanshKing30/FoodiesWeb/assets/106834322/b09c0153-1c11-479e-80a7-4d187cd8108e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Varsani2520** [comment]
can you assign this issue @VanshKing30 

i make a animated hover effect look like a cool

**Comment by VanshKing30** [comment]
@Varsani2520 & @Debarunn1806  Please work on this together and raise the PR when done !!

**Comment by Varsani2520** [comment]
thank you @VanshKing30 for giving me this oppertunity

**Comment by Debarunn1806** [comment]
thankyou for assigning me

**Comment by Debarunn1806** [comment]
Just a quick Question I am not able to view the code for the navbar and other stuff in the root index.html file but when i inspect the page it is visible there . Can you help me on this upon what I am doing wrong.

**Comment by VanshKing30** [comment]
@Debarunn1806 Brother !! The code is writter in React Library not in HTML , Find the Navbar component in Components folder 
file name : Navbar.jsx

**Comment by Debarunn1806** [comment]
Got it thanks

**Comment by Debarunn1806** [comment]
Hello @VanshKing30 I have made a pr kindly review it.

**Comment by Rohansamrat** [comment]
Hi @VanshKing30  can you assign this issue to me

**Comment by Varsani2520** [comment]
Hey @VanshKing30  ,i already solved this issue ,you can check the PR #104 and merged it

**Comment by VanshKing30** [comment]
I will check this !!
