### ISSUE TITLE
improve in signup  ui 

### ISSUE THREAD

**Issue by parikhitritgithub** [VanshKing30/FoodiesWeb#8]
Using Hot-Toast React, I can show a popup for error, success, or an invalid email ,  Here are some  of my works , 
please assign this issue to me  under GSSOC24 
![Screenshot 2024-05-10 014523](https://github.com/VanshKing30/FoodiesWeb/assets/124444610/30a0de08-d3a4-497d-bc37-543df9a32a88)
![Screenshot 2024-05-10 014700](https://github.com/VanshKing30/FoodiesWeb/assets/124444610/739f2764-f5a2-472b-8971-9f19987c8102)
![Screenshot 2024-05-10 014745](https://github.com/VanshKing30/FoodiesWeb/assets/124444610/4bffaf0a-9849-4fc8-8924-6d512d6fc375)
![Screenshot 2024-05-10 014608](https://github.com/VanshKing30/FoodiesWeb/assets/124444610/7172f256-b971-4e40-8c83-f86dc3e1017b)

**Comment by parikhitritgithub** [comment]
@VanshKing30  please assign this issue to me

**Comment by VanshKing30** [comment]
@parikhitritgithub We alredy are using hot toast similar to what you are showing in the screenshots , there's no need . Thank You!!

**Comment by parikhitritgithub** [comment]
Ok , thank you 😊
