### ISSUE TITLE
BUG: The canteen Info cards improvement (UI)

### ISSUE THREAD

**Issue by TejasNasre** [VanshKing30/FoodiesWeb#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The canteen Info cards has not align properly and the size of the cards are not good in mobile device needs improvement :

![Screenshot_2024-05-12-08-14-01-05](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/d4055d5e-a9cf-4c2a-80dc-79722ad81217)

I like to improve the cards and flex to column when it's on mobile device.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
What changes can you make ?? 
Make sure you only change in tailwind css , Vanilla CSS is now allwoed

**Comment by TejasNasre** [comment]
As you can see the cards are get small in mobile devices and so I will flex the card in column when they in small screen size and make more beautiful by padding and margin.
Yes I will use tailwind css only.

Assign me this issue.

**Comment by VanshKing30** [comment]
Assigned you the issue , raise the PR when done

**Comment by TejasNasre** [comment]
Thanks @VanshKing30 I am raising PR soon

**Comment by TejasNasre** [comment]
hey @VanshKing30 i made small change and commit in my forked repo after that i goes for pr but i made pr previously for backend feature and not got merged yet so i can't' make pr now 

![ui isuue](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/55926f76-3a90-4bca-aced-2d98564a631f)

 its showing in pr commit what i should i do now?

**Comment by TejasNasre** [comment]
fixed Ui i made changes successfully : 

less than 768px card showing in column :

![less than](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/02af2367-7907-46bc-81d6-44a5e7e449ae)

greater than 768px card showing in row:

![greater](https://github.com/VanshKing30/FoodiesWeb/assets/113225478/30d649b8-7b89-46d9-a19d-5c1802d4c55d)

**Comment by mtg718** [comment]
Please assign me this issue under GSSoc'24.
