### ISSUE TITLE
Feat:About  us page design 

### ISSUE THREAD

**Issue by AakankshaSarode** [VanshKing30/FoodiesWeb#81]
### Describe the feature

styling  about About page can be improve adding some transition which related to website  and adding some dropdown about questions in about page make it more precise and looking nice and easy to understanding

### Add ScreenShots

![Screenshot 2024-05-12 083526](https://github.com/VanshKing30/FoodiesWeb/assets/142107143/5a1be845-637f-4000-b3a3-6ac33e7c066b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by HARISH-1222** [comment]
Hi @AakankshaSarode 👋, I understand the issue that you raised I can fix this for you. Under GSSOC'24,

**Comment by AakankshaSarode** [comment]
@VanshKing30  I want  work on this issue please assign me this issue under GSSOC'24

**Comment by VanshKing30** [comment]
Updates have alredy made in the aboutus page !
