### ISSUE TITLE
BUG: Card not shown properly in large screen

### ISSUE THREAD

**Issue by dhruv8433** [VanshKing30/FoodiesWeb#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?
@VanshKing30 
check out this image card is not properly arranged in grid layout 

there are still some space available in right side
![image](https://github.com/VanshKing30/FoodiesWeb/assets/114583978/206c4792-9a69-41ac-8f78-95992391b955)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by iritikyadav123** [comment]
I would like to solve this issue.
