### ISSUE TITLE
BUG:Card style changed in responsive

### ISSUE THREAD

**Issue by dhruv8433** [VanshKing30/FoodiesWeb#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@VanshKing30 
in responsive phone design card widht increase 
check this image: 
![image](https://github.com/VanshKing30/FoodiesWeb/assets/114583978/bb03c471-72cf-4af1-9e95-ae592fcd7578)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Can you solve this issue ??

**Comment by dhruv8433** [comment]
@VanshKing30 I would like to work on that please assign me
