### ISSUE TITLE
Feat: Detailed page for each resort

### ISSUE THREAD

**Issue by dhruv8433** [VanshKing30/FoodiesWeb#84]
### Describe the feature

@VanshKing30 
there are detailed page missing for each resort
we can add detailed page that containe resort name, some images, rating, reviews and much more...

### Add ScreenShots

check out this image like this we can add name, rating and picture gallery etc...
![image](https://github.com/VanshKing30/FoodiesWeb/assets/114583978/89dfac7a-b0d1-4992-996e-2e74497d4e17)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Exactly what information about the canteen you want to show ??

**Comment by dhruv8433** [comment]
@VanshKing30 
Like canteen rarings, reviews, one detailed page that contain what's kind of breakfast or launch they provide etc...
