### ISSUE TITLE
redesign the about page

### ISSUE THREAD

**Issue by Kaveyan** [VanshKing30/FoodiesWeb#86]
### Describe the feature

to make attractive

### Add ScreenShots

![Screenshot 2024-05-12 113439](https://github.com/VanshKing30/FoodiesWeb/assets/120024889/f7be38a6-5f07-43de-89e0-fbbeb526004b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Kaveyan** [comment]
assign to me for this work

**Comment by VanshKing30** [comment]
What changes can you make ?? 
The about us page has alredy been changed by some other contributer , please do check the updated one and then if you feel like changing something raise the issue !!

**Comment by Kaveyan** [comment]
okay ,thanks for your information
