### ISSUE TITLE
UI Updation: Adding animations to provide modern look

### ISSUE THREAD

**Issue by StephenStolk** [VanshKing30/FoodiesWeb#87]
### Describe the feature

Tech stack: Using Framer motion
- While loading pages (routing), the page components are looking bland. 
- With animations like 'fade' when the page opens, it will provide a professional look.

### Add ScreenShots

Sample: (example of a fade in)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/bcd206d9-8261-4c2d-8a95-37af3272e098)
![image](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/d95667cb-6e00-4ea9-8018-a9d59a248671)

Another example-
![Screenshot 2024-01-30 235632](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/20bbac93-e4f0-41d3-94ee-68c28224a3ae)
![Screenshot 2024-01-30 235653](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/2fe85270-ebe4-480d-9778-9fa6240a44c5)
![Screenshot 2024-01-30 235713](https://github.com/VanshKing30/FoodiesWeb/assets/134587780/c8da252d-d7ff-45aa-bebd-ed4688845616)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by StephenStolk** [comment]
I want to take up this issue.

**Comment by VanshKing30** [comment]
I am unable to recognize the screenshots. It would be better if you provide me with the live link or a GIF video.

**Comment by StephenStolk** [comment]
@VanshKing30  Sample: https://byte-bhartiye.vercel.app/
You can see the 'motion' of all components when you scroll.

**Comment by VanshKing30** [comment]
For now only add the motion effect in about us page !!

**Comment by VanshKing30** [comment]
This task has alredy been taken by someone !!

**Comment by StephenStolk** [comment]
@VanshKing30  I was suggesting the same thing as #90.  I have been assigned earlier for this and I have almost completed.
