### ISSUE TITLE
Missing CONTRIBUTING.md File in Repository

### ISSUE THREAD

**Issue by suhanipaliwal** [VanshKing30/FoodiesWeb#88]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by VanshKing30** [comment]
Can you please share me the content you will provide me in the Contributing.md file ??

**Comment by ishitapatidar27** [comment]
The contributing.md file will be containing following contents-
 Code of Conduct.
Asking Questions.
Opening an Issue.
Feature Requests.
Triaging Issues.
Submitting Pull Requests.
Writing Commit Messages.
Code Review

could you please assign this to me ? Thankyou

**Comment by deekshithapalla** [comment]
I would like to work on this issue since, CONTRIBUTING.md file plays a crucial part on dealing with issue and PR's.
I would like to add the steps needed to be followed to contribute which includes opening an issue, forking the repository and submitting the PR's.
Please assign this task to me.

**Comment by suhanipaliwal** [comment]
> Can you please share me the content you will provide me in the Contributing.md file ??

The documentation will contain a set of guidelines to help contributors during the contribution process.
It will help first time contributors in forking, cloning and then working on the repository.
I will include instructions for issue report process.
Also instructions for a pull request process will be included.

**Comment by VanshKing30** [comment]
@deekshithapalla @suhanipaliwal @ishitapatidar27 Assigned you the issue !
