### ISSUE TITLE
Add Email Verification for Signup and Login

### ISSUE THREAD

**Issue by Slacky300** [VanshKing30/FoodiesWeb#9]
**Proposal: Implement Email Verification System**

### Objective:
Implement an email verification system for user registration and login processes to enhance security and user experience.

### Key Features:
- **Email Verification Upon Registration:** 
  - Upon registration, the system should automatically send a verification email to the user's provided email address.

- **Login Restriction:** 
  - Until the user verifies their email address, they should not be able to log in to the platform.

- **Notification for Unverified Accounts:**
  - Users attempting to log in without verifying their email address should receive a notification indicating their account is not verified.

- **Resend Verification Email:**
  - Users should have the option to request a new verification email if they haven't received it or have accidentally deleted it.
  - This resend functionality should be easily accessible from the login screen or through the user's account settings.

### Benefits:
- **Enhanced Security:**
  - Only users with verified email addresses can access their accounts, reducing the risk of unauthorized access.

- **Improved User Experience:**
  - Providing users with the option to request a new verification email reduces frustration in case of missed or lost emails.

By implementing this feature, we aim to significantly enhance the security of the platform while improving the overall user experience.

**Comment by ThePlator** [comment]
hey 

I wanna to work on this, 
I have a Question can I use any external services like appwrite or firebase ?

**Comment by developer-kush** [comment]
I can implement this functionality if allowed

**Comment by Yadavanurag13** [comment]
This feature will require the use of an email sending service API, which typically incurs a cost for the service. Are you planning to implement this in the system?

**Comment by Slacky300** [comment]
Implementing an email service doesn't always incur costs. I'll use Gmail's SMTP service along with Nodemailer to send emails. Since the emails we'll be sending are only for verification of the user, we can utilize this solution.

**Comment by Yadavanurag13** [comment]
Ok.  So the step would be like this to set up the nodemailer and the service used will be gmail,  Admin email and password (Generated App password ) will be used to send an email, once the user verifies it, he/she will be redirected to success page otherwise notified with failure and option for again verification would be given to the user. 

I am highly interested to contribute in the project,  Can you assign me

**Comment by parth3083** [comment]
Hello, I am a MERN developer who creates stunning and modern websites.
So I have more experience creating websites that are animated, scroll smoothly, and have more functionality.
The feature that you can achieve using the node mailer, as well as with Google OAuth

**Comment by Isha1233** [comment]
@developer-kush  assign this task to me as I will implement it using mongoDB

**Comment by VanshKing30** [comment]
@Slacky300 I have assigned this issue to you !! Start working on it and raise the PR as soon as the task is done

**Comment by Isha1233** [comment]
Okhy sir thankyou sir

**Comment by sahithi000** [comment]
@VanshKing30 can u please assign  me this issue under GSSOC i will generate PR ASAP

**Comment by VanshKing30** [comment]
@sahithi000 Are you sure ?? If you commit to raise pr in very less time i will assing you

**Comment by Slacky300** [comment]
@VanshKing30, I'll resolve this issue and raise the PR as soon as the task is done.
