### ISSUE TITLE
fade animation in about us section

### ISSUE THREAD

**Issue by dev04sa** [VanshKing30/FoodiesWeb#90]
### Describe the feature

as you can see , currently about us section showing images and texts normally.
we can add animation like image and texts coming from left or right.
@VanshKing30 kindly assign this issue to me.

### Add ScreenShots

https://github.com/VanshKing30/FoodiesWeb/assets/129666293/72195309-4acc-478e-aace-76ce55da40fc

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Can you share what kind what kind of animation you can add in the website in about us page ?? 
Share video

**Comment by dev04sa** [comment]
@VanshKing30  here is the sample video for animation.

https://github.com/VanshKing30/FoodiesWeb/assets/129666293/4120d610-29b4-42be-b783-5310cb7c9c8d

**Comment by VanshKing30** [comment]
Cool !! I have assigned you the issue , Reaise the PR when done
