### ISSUE TITLE
Feat: UI friendly validation on the signup page

### ISSUE THREAD

**Issue by Niharika0104** [VanshKing30/FoodiesWeb#94]
### Describe the feature

I see that the code is already using react-toastify,so it will ui friendly to show the validations using react-toastify.Adding the password strength is making the form unnecessary long.I will show even the strength of the password using react-toastify.

### Add ScreenShots

Instead of overwhelming the form using all these I will show validation in ui friendly manner
<img width="959" alt="register" src="https://github.com/VanshKing30/FoodiesWeb/assets/124892559/acd16be4-7e30-4fb4-832b-1598138dbb78">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Will you be able to solve this issue ?? Even i feel , the validations should be show through toastify

**Comment by Niharika0104** [comment]
@VanshKing30 yup I will be able to solve
