### ISSUE TITLE
BUG: UI Bugs 

### ISSUE THREAD

**Issue by Archiesachin** [VanshKing30/FoodiesWeb#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<h2>1. If the name of the canteen is quite large then the card expands horizontally disrupting the grid UI.</h2>

![Screenshot (987)](https://github.com/VanshKing30/FoodiesWeb/assets/103347688/c7acb962-d98a-40f4-9f99-98d5f634ebd0)

 
<h2>2. I could login with the same email and password for both User and Canteen</h2>

<h2>3. Adding example inputs in the form placeholder so that the canteen owners will know what should be filled in the input boxes</h2>

![Screenshot (989)](https://github.com/VanshKing30/FoodiesWeb/assets/103347688/6627b034-dbcc-446d-abd9-32eea8b6331a)

<h2>4. Padding of the body is not proper</h2>

![Screenshot (988)](https://github.com/VanshKing30/FoodiesWeb/assets/103347688/15779c17-c62d-4ec1-afed-1c66b6f23814)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by VanshKing30** [comment]
Are you willing to work on all 4 of the issues ??

**Comment by Archiesachin** [comment]
> Are you willing to work on all 4 of the issues ??

Yes, i can solve all 4 issues

**Comment by VanshKing30** [comment]
@Archiesachin Messaage me on discord about the approach 
my id : Vansh5238
