### ISSUE TITLE
Feat: want to create a PR template for this repo

### ISSUE THREAD

**Issue by AnitSarkar123** [VanshKing30/FoodiesWeb#96]
### Describe the feature

 it is very hepful for understanding the changes by contributor

### Add ScreenShots

i will provide the screen short with the PR

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VanshKing30** [comment]
Provide the screenshot here !

**Comment by AnitSarkar123** [comment]
[]()![Screenshot_20240512-235153~2.png](https://github.com/VanshKing30/FoodiesWeb/assets/135215478/2be96ae2-b0cd-4e93-bd57-fe005f4d35e7)

What about this

**Comment by VanshKing30** [comment]
Cool Liked it !! Assigned you the issue , start working on it and raise the PR when done !

**Comment by VanshKing30** [comment]
@AnitSarkar123 Have you complete the task ??

**Comment by AnitSarkar123** [comment]
I will give update tomorrow I make it but forgot to make pr 🥲

**Comment by AnitSarkar123** [comment]
Sorry I made it but forgot to make the pr 🥲
